import type { ResourceFiles } from "@/types/resource";

export type ExportFormat = "single-html" | "vanilla-zip" | "react-zip" | "codepen";

export interface ExportOptions {
  format: ExportFormat;
  /** File/folder name, sanitized. */
  fileName: string;
  includeReadme: boolean;
  includeComments: boolean;
  compactWhitespace: boolean;
  includeDependencies: boolean;
  includeDemoPage: boolean;
}

export const DEFAULT_EXPORT_OPTIONS: ExportOptions = {
  format: "single-html",
  fileName: "resource",
  includeReadme: true,
  includeComments: true,
  compactWhitespace: false,
  includeDependencies: true,
  includeDemoPage: true,
};

export interface ExportMeta {
  name: string;
  slug: string;
  description: string;
  dependencies: string[];
  compatibility: string[];
  author: string;
  license: string;
}

/** Conservative, lossless code transforms — never breaks user code. */
export function processCode(
  code: string,
  options: Pick<ExportOptions, "includeComments" | "compactWhitespace">,
  language: "css" | "js" | "html" | "tsx",
): string {
  let output = code;
  if (!options.includeComments) {
    if (language === "css" || language === "html") {
      output = output.replace(/\/\*[\s\S]*?\*\//g, "");
    }
    if (language === "css") {
      output = output.replace(/^\s*\/\/.*$/gm, "");
    }
    if (language === "js" || language === "tsx") {
      // Only strip block comments; line comments may contain URLs.
      output = output.replace(/\/\*[\s\S]*?\*\//g, "");
    }
  }
  if (options.compactWhitespace) {
    if (language === "css") {
      output = output
        .replace(/\s*\{\s*/g, "{")
        .replace(/\s*\}\s*/g, "}")
        .replace(/\s*;\s*/g, ";")
        .replace(/:\s+/g, ": ");
    }
    output = output.replace(/\n{3,}/g, "\n\n").trimEnd() + "\n";
  }
  return output.trimEnd() + "\n";
}

function readmeFor(meta: ExportMeta, files: ResourceFiles, projectKind: "vanilla" | "react"): string {
  const deps = meta.dependencies.length > 0 ? meta.dependencies.join(", ") : "None";
  const lines = [
    `# ${meta.name}`,
    "",
    meta.description,
    "",
    "## Files",
  ];
  if (projectKind === "vanilla") {
    lines.push(
      "- `index.html` — demo page wiring everything together",
      files.css ? "- `styles.css` — component styles" : "",
      files.javascript ? "- `script.js` — behavior and initialization" : "",
      files.react ? "- `React.tsx` — optional React port of the same resource" : "",
    );
  } else {
    lines.push(
      "- `src/components/Resource.tsx` — the resource component",
      files.css ? "- `src/components/resource.css` — component styles" : "",
      "- `src/App.tsx` — demo usage",
    );
  }
  lines.push(
    "",
    "## Run",
    projectKind === "vanilla"
      ? "Open `index.html` directly in a browser, or serve the folder statically."
      : [
          "```bash",
          "npm install",
          "npm run dev",
          "```",
        ].join("\n"),
    "",
    "## Dependencies",
    deps,
    "",
    "## Browser compatibility",
    meta.compatibility.length > 0 ? meta.compatibility.join(", ") : "Modern evergreen browsers.",
    "",
    "## Notes",
    "- Generated by VibeUI.",
    `- Author: ${meta.author} · License: ${meta.license}`,
  );
  return lines.filter((l) => l !== "").join("\n") + "\n";
}

function reactProjectFiles(
  meta: ExportMeta,
  files: ResourceFiles,
  options: ExportOptions,
  componentName: string,
): Record<string, string> {
  const out: Record<string, string> = {};
  const cssImport = files.css
    ? `import "./resource.css";\n`
    : "";
  out["package.json"] = JSON.stringify(
    {
      name: meta.slug,
      private: true,
      version: "0.0.0",
      type: "module",
      scripts: { dev: "vite", build: "tsc && vite build", preview: "vite preview" },
      dependencies: { react: "^18.3.1", "react-dom": "^18.3.1" },
      devDependencies: {
        "@types/react": "^18.3.5",
        "@types/react-dom": "^18.3.0",
        "@vitejs/plugin-react": "^4.3.1",
        typescript: "^5.6.2",
        vite: "^5.4.8",
      },
    },
    null,
    2,
  );
  out["vite.config.ts"] = [
    `import { defineConfig } from "vite";`,
    `import react from "@vitejs/plugin-react";`,
    "",
    "export default defineConfig({",
    "  plugins: [react()],",
    "});",
    "",
  ].join("\n");
  out["tsconfig.json"] = JSON.stringify(
    {
      compilerOptions: {
        target: "ES2020",
        lib: ["DOM", "DOM.Iterable", "ESNext"],
        jsx: "react-jsx",
        module: "ESNext",
        moduleResolution: "bundler",
        strict: true,
        skipLibCheck: true,
        noEmit: true,
      },
      include: ["src"],
    },
    null,
    2,
  );
  out["index.html"] = [
    "<!doctype html>",
    '<html lang="en">',
    "  <head>",
    '    <meta charset="UTF-8" />',
    '    <meta name="viewport" content="width=device-width, initial-scale=1.0" />',
    `    <title>${meta.name}</title>`,
    "  </head>",
    "  <body>",
    '    <div id="root"></div>',
    '    <script type="module" src="/src/main.tsx"></script>',
    "  </body>",
    "</html>",
    "",
  ].join("\n");
  out["src/main.tsx"] = [
    "import React from \"react\";",
    "import ReactDOM from \"react-dom/client\";",
    "import App from \"./App\";",
    "",
    "ReactDOM.createRoot(document.getElementById(\"root\")!).render(",
    "  <React.StrictMode>",
    "    <App />",
    "  </React.StrictMode>,",
    ");",
    "",
  ].join("\n");
  out["src/App.tsx"] = options.includeDemoPage
    ? [
        `${cssImport}import Resource from "./components/Resource";`,
        "",
        "export default function App() {",
        "  return (",
        '    <main style={{ minHeight: "100vh", display: "grid", placeItems: "center", padding: 24 }}>',
        "      <Resource />",
        "    </main>",
        "  );",
        "}",
        "",
      ].join("\n")
    : ["export default function App() {", "  return null;", "}", ""].join("\n");
  out["src/components/Resource.tsx"] = processCode(
    files.react ?? "",
    options,
    "tsx",
  ).replace(/export default function (\w+)/, `export default function ${componentName}`);
  if (files.css) {
    out["src/components/resource.css"] = processCode(files.css, options, "css");
  }
  if (options.includeReadme) {
    out["README.md"] = readmeFor(meta, files, "react");
  }
  return out;
}

function vanillaProjectFiles(
  meta: ExportMeta,
  files: ResourceFiles,
  options: ExportOptions,
): Record<string, string> {
  const out: Record<string, string> = {};
  const css = files.css ? processCode(files.css, options, "css") : "";
  const js = files.javascript ? processCode(files.javascript, options, "js") : "";
  const html = processCode(files.html ?? "", options, "html");
  out["index.html"] = [
    "<!doctype html>",
    '<html lang="en">',
    "<head>",
    '  <meta charset="utf-8" />',
    '  <meta name="viewport" content="width=device-width, initial-scale=1" />',
    `  <title>${meta.name}</title>`,
    css ? '  <link rel="stylesheet" href="./styles.css" />' : "",
    "</head>",
    "<body>",
    html,
    js ? '  <script src="./script.js"></script>' : "",
    "</body>",
    "</html>",
    "",
  ]
    .filter((line) => line !== "")
    .join("\n");
  if (css) out["styles.css"] = css;
  if (js) out["script.js"] = js;
  if (files.react) out["React.tsx"] = processCode(files.react, options, "tsx");
  if (options.includeReadme) out["README.md"] = readmeFor(meta, files, "vanilla");
  if (options.includeDependencies && meta.dependencies.length > 0) {
    out["DEPENDENCIES.md"] =
      [`# Dependencies`, "", ...meta.dependencies.map((d) => `- ${d}`), ""].join("\n");
  }
  return out;
}

export function buildProjectFiles(
  meta: ExportMeta,
  files: ResourceFiles,
  options: ExportOptions,
): Record<string, string> {
  const componentName = meta.slug
    .split(/[-_]/)
    .filter(Boolean)
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join("");
  if (options.format === "react-zip") {
    return reactProjectFiles(meta, files, options, componentName);
  }
  return vanillaProjectFiles(meta, files, options);
}

export function buildSingleHtmlFile(
  meta: ExportMeta,
  files: ResourceFiles,
  options: ExportOptions,
): string {
  const css = files.css ? processCode(files.css, options, "css") : "";
  const js = files.javascript ? processCode(files.javascript, options, "js") : "";
  const html = processCode(files.html ?? "", options, "html");
  return [
    "<!doctype html>",
    '<html lang="en">',
    "<head>",
    '  <meta charset="utf-8" />',
    '  <meta name="viewport" content="width=device-width, initial-scale=1" />',
    `  <title>${meta.name}</title>`,
    css ? "  <style>\n" + indent(css, 4) + "\n  </style>" : "",
    "</head>",
    "<body>",
    indent(html, 2),
    js ? "  <script>\n" + indent(js, 4) + "\n  </script>" : "",
    "</body>",
    "</html>",
    "",
  ]
    .filter((l) => l !== "")
    .join("\n");
}

function indent(code: string, spaces: number): string {
  const pad = " ".repeat(spaces);
  return code
    .split("\n")
    .map((line) => (line.trim() ? pad + line : line))
    .join("\n");
}
