// AUTO-GENERATED by scripts/split-registry-ai.mjs — do not edit by hand.
// Server-only: full handwritten AI layers per slug. The client barrel must NOT
// import this file (prompts/knobs/pitfalls are the heavy part of the bundle).
import type { ResourceAILayer } from "@/types/resource";
import { ai as a0 } from "./animations/aurora-background/ai"; // aurora-background
import { ai as a1 } from "./animations/blob-background/ai"; // blob-background
import { ai as a2 } from "./animations/border-beam/ai"; // border-beam
import { ai as a3 } from "./animations/bounce-in/ai"; // bounce-in
import { ai as a4 } from "./animations/click-spark/ai"; // click-spark
import { ai as a5 } from "./animations/confetti-burst/ai"; // confetti-burst
import { ai as a6 } from "./animations/cursor-glow/ai"; // cursor-glow
import { ai as a7 } from "./animations/elastic-press/ai"; // elastic-press
import { ai as a8 } from "./animations/flip-card/ai"; // flip-card
import { ai as a9 } from "./animations/flip-clock/ai"; // flip-clock
import { ai as a10 } from "./animations/gauge-fill/ai"; // gauge-fill
import { ai as a11 } from "./animations/glitch-text/ai"; // glitch-text
import { ai as a12 } from "./animations/glow-border/ai"; // glow-border
import { ai as a13 } from "./animations/gradient-text/ai"; // gradient-text
import { ai as a14 } from "./animations/grid-background/ai"; // grid-background
import { ai as a15 } from "./animations/kinetic-path-text/ai"; // kinetic-path-text
import { ai as a16 } from "./animations/marquee/ai"; // marquee
import { ai as a17 } from "./animations/mouse-parallax/ai"; // mouse-parallax
import { ai as a18 } from "./animations/number-counter/ai"; // number-counter
import { ai as a19 } from "./animations/page-transition/ai"; // page-transition
import { ai as a20 } from "./animations/particle-flow-field/ai"; // particle-flow-field
import { ai as a21 } from "./animations/pixel-dissolve-reveal/ai"; // pixel-dissolve-reveal
import { ai as a22 } from "./animations/pulse-ring/ai"; // pulse-ring
import { ai as a23 } from "./animations/radar-sweep/ai"; // radar-sweep
import { ai as a24 } from "./animations/reading-progress/ai"; // reading-progress
import { ai as a25 } from "./animations/scroll-reveal/ai"; // scroll-reveal
import { ai as a26 } from "./animations/shake-feedback/ai"; // shake-feedback
import { ai as a27 } from "./animations/shine-sweep/ai"; // shine-sweep
import { ai as a28 } from "./animations/skeleton-shimmer/ai"; // skeleton-shimmer
import { ai as a29 } from "./animations/text-reveal/ai"; // text-reveal
import { ai as a30 } from "./animations/text-rotate/ai"; // text-rotate
import { ai as a31 } from "./animations/text-scramble/ai"; // text-scramble
import { ai as a32 } from "./animations/typewriter/ai"; // typewriter
import { ai as a33 } from "./animations/wave-text/ai"; // wave-text
import { ai as a34 } from "./blocks/announcement-bar/ai"; // announcement-bar
import { ai as a35 } from "./blocks/app-download-cta/ai"; // app-download-cta
import { ai as a36 } from "./blocks/comparison-table/ai"; // comparison-table
import { ai as a37 } from "./blocks/contact-form-section/ai"; // contact-form-section
import { ai as a38 } from "./blocks/cookie-consent/ai"; // cookie-consent
import { ai as a39 } from "./blocks/cta-banner/ai"; // cta-banner
import { ai as a40 } from "./blocks/faq-accordion/ai"; // faq-accordion
import { ai as a41 } from "./blocks/features-grid/ai"; // features-grid
import { ai as a42 } from "./blocks/footer-minimal/ai"; // footer-minimal
import { ai as a43 } from "./blocks/hero-centered/ai"; // hero-centered
import { ai as a44 } from "./blocks/hero-split/ai"; // hero-split
import { ai as a45 } from "./blocks/how-it-works/ai"; // how-it-works
import { ai as a46 } from "./blocks/integrations-grid/ai"; // integrations-grid
import { ai as a47 } from "./blocks/logo-cloud/ai"; // logo-cloud
import { ai as a48 } from "./blocks/newsletter-cta/ai"; // newsletter-cta
import { ai as a49 } from "./blocks/pricing-table/ai"; // pricing-table
import { ai as a50 } from "./blocks/stats-bar/ai"; // stats-bar
import { ai as a51 } from "./blocks/team-section/ai"; // team-section
import { ai as a52 } from "./blocks/testimonial-wall/ai"; // testimonial-wall
import { ai as a53 } from "./blocks/trust-badges/ai"; // trust-badges
import { ai as a54 } from "./components/buttons/border-draw-button/ai"; // border-draw-button
import { ai as a55 } from "./components/buttons/hold-to-confirm/ai"; // hold-to-confirm
import { ai as a56 } from "./components/buttons/liquid-button/ai"; // liquid-button
import { ai as a57 } from "./components/buttons/loading-button/ai"; // loading-button
import { ai as a58 } from "./components/buttons/magnetic-button/ai"; // magnetic-button
import { ai as a59 } from "./components/buttons/ripple-button/ai"; // ripple-button
import { ai as a60 } from "./components/buttons/split-button/ai"; // split-button
import { ai as a61 } from "./components/cards/article-card/ai"; // article-card
import { ai as a62 } from "./components/cards/code-snippet-card/ai"; // code-snippet-card
import { ai as a63 } from "./components/cards/course-card/ai"; // course-card
import { ai as a64 } from "./components/cards/donut-chart/ai"; // donut-chart
import { ai as a65 } from "./components/cards/expandable-card/ai"; // expandable-card
import { ai as a66 } from "./components/cards/file-card/ai"; // file-card
import { ai as a67 } from "./components/cards/flight-card/ai"; // flight-card
import { ai as a68 } from "./components/cards/glass-card/ai"; // glass-card
import { ai as a69 } from "./components/cards/image-comparison/ai"; // image-comparison
import { ai as a70 } from "./components/cards/invoice-card/ai"; // invoice-card
import { ai as a71 } from "./components/cards/job-card/ai"; // job-card
import { ai as a72 } from "./components/cards/music-player-card/ai"; // music-player-card
import { ai as a73 } from "./components/cards/notification-card/ai"; // notification-card
import { ai as a74 } from "./components/cards/order-tracking-card/ai"; // order-tracking-card
import { ai as a75 } from "./components/cards/podcast-card/ai"; // podcast-card
import { ai as a76 } from "./components/cards/product-card/ai"; // product-card
import { ai as a77 } from "./components/cards/profile-card/ai"; // profile-card
import { ai as a78 } from "./components/cards/shared-layout-gallery/ai"; // shared-layout-gallery
import { ai as a79 } from "./components/cards/sparkline-chart/ai"; // sparkline-chart
import { ai as a80 } from "./components/cards/spotlight-card/ai"; // spotlight-card
import { ai as a81 } from "./components/cards/stats-card/ai"; // stats-card
import { ai as a82 } from "./components/cards/tilt-card/ai"; // tilt-card
import { ai as a83 } from "./components/cards/wallet-card/ai"; // wallet-card
import { ai as a84 } from "./components/cards/weather-card/ai"; // weather-card
import { ai as a85 } from "./components/forms/auto-textarea/ai"; // auto-textarea
import { ai as a86 } from "./components/forms/color-picker/ai"; // color-picker
import { ai as a87 } from "./components/forms/combobox-autocomplete/ai"; // combobox-autocomplete
import { ai as a88 } from "./components/forms/currency-input/ai"; // currency-input
import { ai as a89 } from "./components/forms/date-picker/ai"; // date-picker
import { ai as a90 } from "./components/forms/emoji-picker/ai"; // emoji-picker
import { ai as a91 } from "./components/forms/file-upload/ai"; // file-upload
import { ai as a92 } from "./components/forms/floating-label-input/ai"; // floating-label-input
import { ai as a93 } from "./components/forms/inline-edit/ai"; // inline-edit
import { ai as a94 } from "./components/forms/mention-input/ai"; // mention-input
import { ai as a95 } from "./components/forms/multi-select/ai"; // multi-select
import { ai as a96 } from "./components/forms/multi-step-form/ai"; // multi-step-form
import { ai as a98 } from "./components/forms/otp-input/ai"; // otp-input
import { ai as a99 } from "./components/forms/password-strength/ai"; // password-strength
import { ai as a100 } from "./components/forms/range-slider/ai"; // range-slider
import { ai as a101 } from "./components/forms/search-input/ai"; // search-input
import { ai as a102 } from "./components/forms/stepper-input/ai"; // stepper-input
import { ai as a103 } from "./components/forms/tag-input/ai"; // tag-input
import { ai as a104 } from "./components/forms/tree-select/ai"; // tree-select
import { ai as a105 } from "./components/navigation/animated-tabs/ai"; // animated-tabs
import { ai as a106 } from "./components/navigation/bottom-sheet/ai"; // bottom-sheet
import { ai as a107 } from "./components/navigation/breadcrumb/ai"; // breadcrumb
import { ai as a108 } from "./components/navigation/collapsible-sidebar/ai"; // collapsible-sidebar
import { ai as a109 } from "./components/navigation/command-menu/ai"; // command-menu
import { ai as a110 } from "./components/navigation/drawer/ai"; // drawer
import { ai as a111 } from "./components/navigation/dropdown-menu/ai"; // dropdown-menu
import { ai as a112 } from "./components/navigation/filters-sidebar/ai"; // filters-sidebar
import { ai as a113 } from "./components/navigation/floating-dock/ai"; // floating-dock
import { ai as a114 } from "./components/navigation/gooey-morph-menu/ai"; // gooey-morph-menu
import { ai as a115 } from "./components/navigation/mega-menu/ai"; // mega-menu
import { ai as a116 } from "./components/navigation/minimal-navbar/ai"; // minimal-navbar
import { ai as a117 } from "./components/navigation/mobile-menu/ai"; // mobile-menu
import { ai as a118 } from "./components/navigation/pagination/ai"; // pagination
import { ai as a119 } from "./components/navigation/scroll-spy/ai"; // scroll-spy
import { ai as a120 } from "./components/navigation/step-nav/ai"; // step-nav
import { ai as a121 } from "./components/navigation/tree-menu/ai"; // tree-menu
import { ai as a122 } from "./components/primitives/accordion/ai"; // accordion
import { ai as a123 } from "./components/primitives/badge-chip/ai"; // badge-chip
import { ai as a124 } from "./components/primitives/callout/ai"; // callout
import { ai as a125 } from "./components/primitives/checkbox-card/ai"; // checkbox-card
import { ai as a126 } from "./components/primitives/context-menu/ai"; // context-menu
import { ai as a127 } from "./components/primitives/copy-button/ai"; // copy-button
import { ai as a128 } from "./components/primitives/countdown-timer/ai"; // countdown-timer
import { ai as a129 } from "./components/primitives/counter-badge/ai"; // counter-badge
import { ai as a130 } from "./components/primitives/heat-map-calendar/ai"; // heat-map-calendar
import { ai as a131 } from "./components/primitives/kbd-shortcut/ai"; // kbd-shortcut
import { ai as a132 } from "./components/primitives/link-hover/ai"; // link-hover
import { ai as a133 } from "./components/primitives/popover/ai"; // popover
import { ai as a134 } from "./components/primitives/rating-stars/ai"; // rating-stars
import { ai as a135 } from "./components/primitives/scroll-shadow/ai"; // scroll-shadow
import { ai as a136 } from "./components/primitives/scroll-to-top/ai"; // scroll-to-top
import { ai as a137 } from "./components/primitives/segmented-control/ai"; // segmented-control
import { ai as a138 } from "./components/primitives/speed-dial/ai"; // speed-dial
import { ai as a139 } from "./components/primitives/spinner-set/ai"; // spinner-set
import { ai as a140 } from "./components/primitives/theme-toggle/ai"; // theme-toggle
import { ai as a141 } from "./components/primitives/timeline/ai"; // timeline
import { ai as a142 } from "./components/primitives/toast-stack/ai"; // toast-stack
import { ai as a143 } from "./components/primitives/toggle-group/ai"; // toggle-group
import { ai as a144 } from "./components/primitives/toggle-switch/ai"; // toggle-switch
import { ai as a145 } from "./components/primitives/tooltip-css/ai"; // tooltip-css
import { ai as a146 } from "./components/progress/circular-progress/ai"; // circular-progress
import { ai as a147 } from "./components/progress/dot-loader/ai"; // dot-loader
import { ai as a148 } from "./components/progress/linear-progress/ai"; // linear-progress
import { ai as a149 } from "./components/progress/multi-step-progress/ai"; // multi-step-progress
import { ai as a150 } from "./components/progress/page-loader/ai"; // page-loader
import { ai as a151 } from "./components/progress/scroll-progress/ai"; // scroll-progress
import { ai as a152 } from "./components/progress/skeleton-card/ai"; // skeleton-card
import { ai as a153 } from "./components/progress/skeleton-table/ai"; // skeleton-table
import { ai as a154 } from "./components/progress/upload-progress/ai"; // upload-progress
import { ai as a155 } from "./icons/logo-marks/logo-bolt-hex/ai"; // logo-bolt-hex
import { ai as a156 } from "./icons/logo-marks/logo-diamond-stack/ai"; // logo-diamond-stack
import { ai as a157 } from "./icons/logo-marks/logo-hive/ai"; // logo-hive
import { ai as a158 } from "./icons/logo-marks/logo-leaf-ring/ai"; // logo-leaf-ring
import { ai as a159 } from "./icons/logo-marks/logo-orbit/ai"; // logo-orbit
import { ai as a160 } from "./icons/logo-marks/logo-sun-mark/ai"; // logo-sun-mark
import { ai as a161 } from "./icons/logo-marks/logo-tri-prism/ai"; // logo-tri-prism
import { ai as a162 } from "./icons/logo-marks/logo-wave-shield/ai"; // logo-wave-shield
import { ai as a163 } from "./templates/404-page/ai"; // 404-page
import { ai as a164 } from "./templates/analytics-dashboard/ai"; // analytics-dashboard
import { ai as a165 } from "./templates/blog-home/ai"; // blog-home
import { ai as a166 } from "./templates/changelog-page/ai"; // changelog-page
import { ai as a167 } from "./templates/checkout-page/ai"; // checkout-page
import { ai as a168 } from "./templates/coming-soon/ai"; // coming-soon
import { ai as a169 } from "./templates/docs-page/ai"; // docs-page
import { ai as a170 } from "./templates/empty-state/ai"; // empty-state
import { ai as a171 } from "./templates/gallery-page/ai"; // gallery-page
import { ai as a172 } from "./templates/help-center/ai"; // help-center
import { ai as a173 } from "./templates/kanban-board/ai"; // kanban-board
import { ai as a174 } from "./templates/login-page/ai"; // login-page
import { ai as a175 } from "./templates/portfolio-home/ai"; // portfolio-home
import { ai as a176 } from "./templates/pricing-page/ai"; // pricing-page
import { ai as a177 } from "./templates/product-detail/ai"; // product-detail
import { ai as a178 } from "./templates/saas-landing/ai"; // saas-landing
import { ai as a179 } from "./templates/settings-template/ai"; // settings-template
import { ai as a180 } from "./templates/status-page/ai"; // status-page
import { ai as a181 } from "./templates/team-page/ai"; // team-page
import { ai as npsScaleAI } from "./components/forms/nps-scale/ai"; // nps-scale

export const AI_DATA: Record<string, ResourceAILayer> = {
  "nps-scale": npsScaleAI,
  "aurora-background": a0,
  "blob-background": a1,
  "border-beam": a2,
  "bounce-in": a3,
  "click-spark": a4,
  "confetti-burst": a5,
  "cursor-glow": a6,
  "elastic-press": a7,
  "flip-card": a8,
  "flip-clock": a9,
  "gauge-fill": a10,
  "glitch-text": a11,
  "glow-border": a12,
  "gradient-text": a13,
  "grid-background": a14,
  "kinetic-path-text": a15,
  "marquee": a16,
  "mouse-parallax": a17,
  "number-counter": a18,
  "page-transition": a19,
  "particle-flow-field": a20,
  "pixel-dissolve-reveal": a21,
  "pulse-ring": a22,
  "radar-sweep": a23,
  "reading-progress": a24,
  "scroll-reveal": a25,
  "shake-feedback": a26,
  "shine-sweep": a27,
  "skeleton-shimmer": a28,
  "text-reveal": a29,
  "text-rotate": a30,
  "text-scramble": a31,
  "typewriter": a32,
  "wave-text": a33,
  "announcement-bar": a34,
  "app-download-cta": a35,
  "comparison-table": a36,
  "contact-form-section": a37,
  "cookie-consent": a38,
  "cta-banner": a39,
  "faq-accordion": a40,
  "features-grid": a41,
  "footer-minimal": a42,
  "hero-centered": a43,
  "hero-split": a44,
  "how-it-works": a45,
  "integrations-grid": a46,
  "logo-cloud": a47,
  "newsletter-cta": a48,
  "pricing-table": a49,
  "stats-bar": a50,
  "team-section": a51,
  "testimonial-wall": a52,
  "trust-badges": a53,
  "border-draw-button": a54,
  "hold-to-confirm": a55,
  "liquid-button": a56,
  "loading-button": a57,
  "magnetic-button": a58,
  "ripple-button": a59,
  "split-button": a60,
  "article-card": a61,
  "code-snippet-card": a62,
  "course-card": a63,
  "donut-chart": a64,
  "expandable-card": a65,
  "file-card": a66,
  "flight-card": a67,
  "glass-card": a68,
  "image-comparison": a69,
  "invoice-card": a70,
  "job-card": a71,
  "music-player-card": a72,
  "notification-card": a73,
  "order-tracking-card": a74,
  "podcast-card": a75,
  "product-card": a76,
  "profile-card": a77,
  "shared-layout-gallery": a78,
  "sparkline-chart": a79,
  "spotlight-card": a80,
  "stats-card": a81,
  "tilt-card": a82,
  "wallet-card": a83,
  "weather-card": a84,
  "auto-textarea": a85,
  "color-picker": a86,
  "combobox-autocomplete": a87,
  "currency-input": a88,
  "date-picker": a89,
  "emoji-picker": a90,
  "file-upload": a91,
  "floating-label-input": a92,
  "inline-edit": a93,
  "mention-input": a94,
  "multi-select": a95,
  "multi-step-form": a96,
  "otp-input": a98,
  "password-strength": a99,
  "range-slider": a100,
  "search-input": a101,
  "stepper-input": a102,
  "tag-input": a103,
  "tree-select": a104,
  "animated-tabs": a105,
  "bottom-sheet": a106,
  "breadcrumb": a107,
  "collapsible-sidebar": a108,
  "command-menu": a109,
  "drawer": a110,
  "dropdown-menu": a111,
  "filters-sidebar": a112,
  "floating-dock": a113,
  "gooey-morph-menu": a114,
  "mega-menu": a115,
  "minimal-navbar": a116,
  "mobile-menu": a117,
  "pagination": a118,
  "scroll-spy": a119,
  "step-nav": a120,
  "tree-menu": a121,
  "accordion": a122,
  "badge-chip": a123,
  "callout": a124,
  "checkbox-card": a125,
  "context-menu": a126,
  "copy-button": a127,
  "countdown-timer": a128,
  "counter-badge": a129,
  "heat-map-calendar": a130,
  "kbd-shortcut": a131,
  "link-hover": a132,
  "popover": a133,
  "rating-stars": a134,
  "scroll-shadow": a135,
  "scroll-to-top": a136,
  "segmented-control": a137,
  "speed-dial": a138,
  "spinner-set": a139,
  "theme-toggle": a140,
  "timeline": a141,
  "toast-stack": a142,
  "toggle-group": a143,
  "toggle-switch": a144,
  "tooltip-css": a145,
  "circular-progress": a146,
  "dot-loader": a147,
  "linear-progress": a148,
  "multi-step-progress": a149,
  "page-loader": a150,
  "scroll-progress": a151,
  "skeleton-card": a152,
  "skeleton-table": a153,
  "upload-progress": a154,
  "logo-bolt-hex": a155,
  "logo-diamond-stack": a156,
  "logo-hive": a157,
  "logo-leaf-ring": a158,
  "logo-orbit": a159,
  "logo-sun-mark": a160,
  "logo-tri-prism": a161,
  "logo-wave-shield": a162,
  "404-page": a163,
  "analytics-dashboard": a164,
  "blog-home": a165,
  "changelog-page": a166,
  "checkout-page": a167,
  "coming-soon": a168,
  "docs-page": a169,
  "empty-state": a170,
  "gallery-page": a171,
  "help-center": a172,
  "kanban-board": a173,
  "login-page": a174,
  "portfolio-home": a175,
  "pricing-page": a176,
  "product-detail": a177,
  "saas-landing": a178,
  "settings-template": a179,
  "status-page": a180,
  "team-page": a181,
};
