// AUTO-GENERATED by scripts/split-registry-ai.mjs — do not edit by hand.
// Client-safe search index: only terms + effectTags per slug (no prose).
import type { ResourceTerms } from "@/types/resource";

export const AI_TERMS: Record<string, { terms: ResourceTerms; effectTags?: string[] }> = {
  "nps-scale": {
    "terms": {
      "zh": "NPS 评分条",
      "en": "NPS Score Scale",
      "aliases": ["净推荐值", "NPS 组件", "推荐值评分", "nps scale"],
      "pattern": "Form · Semantic Score Scale",
      "principle": "0-10 十一档圆形刻度按 NPS 语义分三段着色（贬损/中立/推荐），选中放大反色并展开追问区，提交按钮随文本输入解锁。"
    },
    "effectTags": ["评分", "表单", "NPS"]
  },
  "aurora-background": {
    "terms": {
      "zh": "极光背景",
      "en": "Aurora Background",
      "aliases": [
        "Mesh Gradient",
        "Gradient Blur Blob",
        "Ambient Background",
        "流光背景",
        "弥散光背景"
      ],
      "pattern": "Ambient Motion · Layered Blur",
      "principle": "多个大尺寸径向渐变色块以不同速率、不同方向缓慢漂移，外层统一施加大半径模糊与饱和度提升，叠加后混合出连续流动的极光感。"
    },
    "effectTags": [
      "背景",
      "氛围",
      "渐变",
      "漂移"
    ]
  },
  "blob-background": {
    "terms": {
      "zh": "果冻斑块背景",
      "en": "Blob Background",
      "aliases": [
        "色斑背景",
        "液态渐变",
        "有机 blob"
      ],
      "pattern": "Background · Organic Blob",
      "principle": "三个大尺寸纯色圆块叠在同一层上做 52px 高斯模糊 + 1.15 饱和提升，各自 keyframes 缓慢平移旋转的同时用 border-radius 八值语法关键帧往复形变，产生果冻呼吸感；前景内容 z-index 浮于其上。"
    },
    "effectTags": [
      "背景",
      "色斑",
      "果冻",
      "hero"
    ]
  },
  "border-beam": {
    "terms": {
      "zh": "边框光束",
      "en": "Border Beam",
      "aliases": [
        "边框流光",
        "巡游光点",
        "Magic Border"
      ],
      "pattern": "Border · Conic Orbit",
      "principle": "@property 注册 --bb-angle 为 <angle> 使 conic-gradient 起始角可插值，keyframes 把它从 0deg 转到 360deg 驱动光点巡游，再用 mask-composite: exclude 双层遮罩把渐变裁剪到 1.5px 边框环。"
    },
    "effectTags": [
      "边框",
      "光束",
      "巡游",
      "conic"
    ]
  },
  "bounce-in": {
    "terms": {
      "zh": "弹性入场",
      "en": "Bounce In",
      "aliases": [
        "弹入",
        "过冲入场",
        "pop in"
      ],
      "pattern": "Bounce · Overshoot Entrance",
      "principle": "关键帧在 100% 前插入 108% 与 97% 两个过冲点（cubic-bezier 难做的弹性感），元素从 scale(.3) opacity 0 起跳；每个子元素用 --bi-delay 负值或递增正值错峰。"
    },
    "effectTags": [
      "弹性",
      "入场",
      "错峰"
    ]
  },
  "click-spark": {
    "terms": {
      "zh": "点击火花",
      "en": "Click Spark / Click Burst",
      "aliases": [
        "Click Particles",
        "Spark Burst",
        "点击粒子",
        "迸发效果"
      ],
      "pattern": "Micro-interaction · Pointer Feedback",
      "principle": "监听 pointerdown，在点击坐标放一个定位容器，向四周发射 N 条带旋转角的线段粒子；粒子沿各自角度位移淡出，动画结束后立即从 DOM 移除。"
    },
    "effectTags": [
      "点击",
      "反馈",
      "粒子",
      "微交互"
    ]
  },
  "confetti-burst": {
    "terms": {
      "zh": "纸屑庆祝",
      "en": "Confetti Burst",
      "aliases": [
        "彩带喷射",
        "庆祝纸屑",
        "撒花"
      ],
      "pattern": "Canvas · Particle Celebration",
      "principle": "点击点一次性生成 110 片粒子，随机角度速度（4–11）向上抛出，每帧加重力 0.16 与 0.992 空气阻力，rotate 自转 + scale(1, 0.55+0.45·sin(wobble)) 压扁摆动模拟纸片翻面飘落，出界后过滤回收、粒子清空即停 rAF。"
    },
    "effectTags": [
      "纸屑",
      "庆祝",
      "粒子",
      "Canvas"
    ]
  },
  "cursor-glow": {
    "terms": {
      "zh": "光标辉光",
      "en": "Cursor Glow / Spotlight",
      "aliases": [
        "鼠标聚光",
        "跟随光晕",
        "手电筒效果"
      ],
      "pattern": "Cursor · Spotlight Follow",
      "principle": "pointermove 经 rAF 节流后把指针坐标写入 --cg-x/--cg-y 自定义属性，overlay 层的 radial-gradient(340px circle at …) 消费坐标，光晕随之移动而无需改 DOM。"
    },
    "effectTags": [
      "光标",
      "辉光",
      "聚光",
      "跟随"
    ]
  },
  "elastic-press": {
    "terms": {
      "zh": "弹簧按压",
      "en": "Elastic Press / Spring Physics Button",
      "aliases": [
        "Spring Button",
        "物理回弹",
        "弹簧按钮"
      ],
      "pattern": "Micro-interaction · Spring Physics",
      "principle": "按下时把目标 scale 设为 0.88，松开后通过弹簧方程（力 = 刚度 × 位移差）积分更新，叠加阻尼衰减，产生轻微过冲再归位的物理回弹。"
    },
    "effectTags": [
      "弹簧",
      "按压",
      "物理",
      "按钮"
    ]
  },
  "flip-card": {
    "terms": {
      "zh": "3D 翻转卡",
      "en": "Flip Card",
      "aliases": [
        "翻转卡片",
        "正反面卡片",
        "card flip"
      ],
      "pattern": "Flip · 3D RotateY Reveal",
      "principle": "外层容器 perspective 提供透视，内层 transform-style: preserve-3d + hover 时 rotateY(180deg)；正反两面都 backface-visibility: hidden，背面预先 rotateY(180deg)，翻转后恰好朝向用户。"
    },
    "effectTags": [
      "翻转",
      "3D",
      "悬停"
    ]
  },
  "flip-clock": {
    "terms": {
      "zh": "翻页时钟",
      "en": "Flip Clock",
      "aliases": [
        "翻牌时钟",
        "翻页数字",
        "flip counter"
      ],
      "pattern": "Flip Clock · Split-card 3D Flip",
      "principle": "每位数字由「静态上半 + 静态下半」和「动态翻页叶（上半起、下半落）」组成；换数时叶子的上半从 0° 翻到 -90°（露出新数字上半），下半随后从 90° 翻到 0°（露出新数字下半），rotateX + transform-origin 上下边。"
    },
    "effectTags": [
      "翻页",
      "时钟",
      "3D"
    ]
  },
  "gauge-fill": {
    "terms": {
      "zh": "仪表盘扫动",
      "en": "Gauge Fill",
      "aliases": [
        "仪表动画",
        "圆弧进度",
        "gauge chart"
      ],
      "pattern": "Gauge · Arc Sweep + Needle",
      "principle": "SVG 半圆用 stroke-dasharray = 弧长，dashoffset 从满偏扫到目标值实现描边生长；指针 group 用 transform rotate 按 percent×180° 摆动，两者共享同一个 easeOutCubic 进度；中心数字同步滚动。"
    },
    "effectTags": [
      "仪表盘",
      "指针",
      "数值"
    ]
  },
  "glitch-text": {
    "terms": {
      "zh": "故障风文字",
      "en": "Glitch Text",
      "aliases": [
        "信号干扰",
        "毛刺文字",
        "glitch effect"
      ],
      "pattern": "Glitch · RGB Split + Clip Slice",
      "principle": "主体文字的 ::before/::after 用 attr(data-text) 复制同一份文字，分别染青色与红色并负偏移叠加；clip-path inset 按不规则关键帧随机裁切出「抽掉一条」的错觉；主文字自身再做亚像素位移。"
    },
    "effectTags": [
      "故障风",
      "文字动画",
      "色散"
    ]
  },
  "glow-border": {
    "terms": {
      "zh": "辉光描边",
      "en": "Glow Border / Mouse-follow Border",
      "aliases": [
        "发光边框",
        "鼠标辉光描边",
        "Glowing Border"
      ],
      "pattern": "Hover · Mouse-follow Glow",
      "principle": "pointermove 把指针坐标写入 --x/--y，外层卡片的径向渐变背景（220px circle at var(--x) var(--y)）经 1.5px padding 与内层实心卡片叠加后只在边缘透出，形成跟随鼠标的发光描边。"
    },
    "effectTags": [
      "辉光",
      "边框",
      "鼠标跟随",
      "hover"
    ]
  },
  "gradient-text": {
    "terms": {
      "zh": "渐变流动文字",
      "en": "Animated Gradient Text",
      "aliases": [
        "流光文字",
        "渐变标题",
        "Aurora Text"
      ],
      "pattern": "Text · Gradient Flow",
      "principle": "background-clip: text + color: transparent 让线性渐变只显示在文字字形内，background-size 横向放大到 220% 后用 keyframes 把 background-position 从 0% 匀速移到 -220% 实现无缝流动循环。"
    },
    "effectTags": [
      "渐变",
      "文字",
      "流光",
      "hero"
    ]
  },
  "grid-background": {
    "terms": {
      "zh": "动态网格背景",
      "en": "Animated Grid Background",
      "aliases": [
        "蓝图网格",
        "网格扫光背景",
        "Blueprint Grid"
      ],
      "pattern": "Background · Layered Gradients",
      "principle": "两个 1px linear-gradient 以 44px 平铺出横竖网格，叠加 radial-gradient 晕影与 mask 径向渐隐；高亮带是 240px 高的渐变背景图用 background-position 从 -240px 匀速移到 100%+240px 实现循环扫过。"
    },
    "effectTags": [
      "背景",
      "网格",
      "扫光",
      "蓝图"
    ]
  },
  "kinetic-path-text": {
    "terms": {
      "zh": "动力路径文字",
      "en": "Kinetic Path Text",
      "aliases": [
        "路径文字",
        "SVG 文字流",
        "Text on Path"
      ],
      "pattern": "SVG · Kinetic Typography",
      "principle": "三条 SVG path 每帧重算 d 属性实时弯曲，textPath 的 startOffset 按 velocity（0.42 基速 + 指针横向动量）推进并在 -420/-40 区间回绕实现无限循环，三层以 factors 1/-0.74/0.88 差速反向。"
    },
    "effectTags": [
      "SVG",
      "路径文字",
      "惯性",
      "动态排版"
    ]
  },
  "marquee": {
    "terms": {
      "zh": "无限跑马灯",
      "en": "Infinite Marquee",
      "aliases": [
        "滚动播报",
        "无缝循环",
        "Logo 墙滚动"
      ],
      "pattern": "Loop · Seamless Marquee",
      "principle": "内容复制一份让轨道宽度翻倍，keyframes 把 track translate3d(-50%) linear infinite，正好走完一组内容的距离实现无缝循环，两侧用 mask-image 渐变做淡入淡出。"
    },
    "effectTags": [
      "跑马灯",
      "无限循环",
      "播报",
      "标志墙"
    ]
  },
  "mouse-parallax": {
    "terms": {
      "zh": "指针视差",
      "en": "Mouse Parallax",
      "aliases": [
        "鼠标视差",
        "多层视差",
        "深度视差"
      ],
      "pattern": "Pointer · Layered Parallax",
      "principle": "指针位置归一化为 -1~1 作为目标值，rAF 里用 current += (target - current) × 0.08 缓动逼近，各层按 data-depth 乘系数后输出 translate3d 走 GPU 合成，离场目标归零自动回中。"
    },
    "effectTags": [
      "视差",
      "指针跟随",
      "层次",
      "缓动"
    ]
  },
  "number-counter": {
    "terms": {
      "zh": "数字滚动计数",
      "en": "Number Count-Up",
      "aliases": [
        "Odometer",
        "Count Up",
        "Stat Counter",
        "数字动画",
        "里程表"
      ],
      "pattern": "Scroll-triggered Animation · Data Reveal",
      "principle": "元素进入视口后用 requestAnimationFrame 在固定时长内按缓动函数插值，把 0 到目标值之间的每一帧结果写回文本节点，形成滚动逼近的观感。"
    },
    "effectTags": [
      "数字",
      "滚动触发",
      "计数",
      "数据展示"
    ]
  },
  "page-transition": {
    "terms": {
      "zh": "页面转场",
      "en": "Page Transition",
      "aliases": [
        "路由转场",
        "视图切换动画",
        "SPA Transition"
      ],
      "pattern": "Navigation · Exit-then-Enter",
      "principle": "旧页加 .is-exiting 播 0.2s 淡出上移，animationend 后隐藏旧页、显示新页并加 .is-entering 播 0.26s 自下升起，busy 标志位防止连点时两次转场重叠。"
    },
    "effectTags": [
      "转场",
      "路由",
      "SPA",
      "导航"
    ]
  },
  "particle-flow-field": {
    "terms": {
      "zh": "粒子丝线流场",
      "en": "Particle Flow Field",
      "aliases": [
        "流场粒子",
        "向量场丝线",
        "Perlin Flow"
      ],
      "pattern": "Canvas · Flow Field",
      "principle": "每个粒子按 sin/cos 叠加的角度场取方向，速度做 0.91 摩擦衰减后画 px→x 短线段；画布不清屏而是盖一层 5.5%–8.2% 半透明底色，让轨迹拖出丝线残影。"
    },
    "effectTags": [
      "粒子",
      "流场",
      "生成艺术",
      "Canvas"
    ]
  },
  "pixel-dissolve-reveal": {
    "terms": {
      "zh": "像素溶解显现",
      "en": "Pixel Dissolve Reveal",
      "aliases": [
        "像素揭示",
        "马赛克溶解",
        "Pixelate Reveal"
      ],
      "pattern": "Canvas · Pixel Dissolve",
      "principle": "Canvas 以 6px 网格逐格绘制，预生成哈希噪声扰动每个格子的溶解阈值，自动模式下溶解前沿沿对角线 ping-pong 推进，鼠标模式下以指针为圆心的半径揭示，边缘用 smoothstep 混出颗粒过渡带。"
    },
    "effectTags": [
      "像素",
      "溶解",
      "Canvas",
      "揭示"
    ]
  },
  "pulse-ring": {
    "terms": {
      "zh": "脉冲扩散环",
      "en": "Pulse Ring / Pulsating Dot",
      "aliases": [
        "脉冲点",
        "呼吸扩散",
        "雷达波纹点"
      ],
      "pattern": "Indicator · Pulse Ripple",
      "principle": "状态圆点的 ::before/::after 伪元素继承 background，用 keyframes 同时做 scale 放大与 opacity 淡出，两层伪元素错开 0.66s 延迟形成连绵波纹。"
    },
    "effectTags": [
      "脉冲",
      "状态点",
      "扩散",
      "直播"
    ]
  },
  "radar-sweep": {
    "terms": {
      "zh": "雷达扫描",
      "en": "Radar Sweep",
      "aliases": [
        "扫描线",
        "雷达图动画",
        "radar effect"
      ],
      "pattern": "Radar · Conic Sweep",
      "principle": "conic-gradient(from 0deg, 高色→透明 60°) 的圆形层做 rotate 无限旋转形成扫掠扇叶；底座是同心圆环 + 十字线的深色面板；目标点用带延迟的 opacity 闪烁，模拟被扫到时点亮。"
    },
    "effectTags": [
      "雷达",
      "扫描",
      "监控"
    ]
  },
  "reading-progress": {
    "terms": {
      "zh": "阅读进度条",
      "en": "Scroll Progress Bar",
      "aliases": [
        "顶部进度条",
        "阅读指示器",
        "reading progress"
      ],
      "pattern": "Scroll Progress · Top Affordance",
      "principle": "scroll 事件里只置一个脏标记，真正的宽度计算放进 rAF 回调（每帧最多一次）；进度 = scrollTop / (scrollHeight - clientHeight)；超过 60% 后切强调色渐变给出「快读完了」的暗示。"
    },
    "effectTags": [
      "进度条",
      "滚动",
      "性能"
    ]
  },
  "scroll-reveal": {
    "terms": {
      "zh": "滚动显现",
      "en": "Scroll Reveal",
      "aliases": [
        "滚动入场",
        "进入视口动画",
        "Scroll Into View"
      ],
      "pattern": "Scroll · Reveal on Enter",
      "principle": "IntersectionObserver 监听元素进入视口（threshold 0.25）后添加 .is-visible 类并 unobserve，CSS transition 把 opacity 0 → 1、translateY(18px) → 0 过渡出来，配合 transition-delay 做级联。"
    },
    "effectTags": [
      "滚动",
      "显现",
      "入场",
      "级联"
    ]
  },
  "shake-feedback": {
    "terms": {
      "zh": "错误抖动反馈",
      "en": "Shake Feedback / Error Shake",
      "aliases": [
        "表单抖动",
        "错误摇晃",
        "Invalid Shake"
      ],
      "pattern": "Form · Error Shake",
      "principle": "校验失败时给字段容器加 .shake 类，keyframes 在 ±1.5–5px 间先放大后收敛的 8 档 translateX 摆动 0.42s；重连点可重播靠先移除类、void offsetWidth 强制 reflow 再加回；同步 aria-invalid + role=alert 文案。"
    },
    "effectTags": [
      "抖动",
      "表单",
      "错误反馈",
      "无障碍"
    ]
  },
  "shine-sweep": {
    "terms": {
      "zh": "扫光高光",
      "en": "Shine Sweep / Shine Effect",
      "aliases": [
        "扫过光",
        "流光",
        "高光扫过",
        "Shimmer 扫光"
      ],
      "pattern": "Surface · Shine Sweep",
      "principle": "容器 overflow: hidden 裁切一根 skewX 倾斜的白色渐变 ::after 光带，hover 时用 left 过渡或 keyframes 让光带从 -80% 滑到 130% 掠过表面。"
    },
    "effectTags": [
      "扫光",
      "高光",
      "hover",
      "加载占位"
    ]
  },
  "skeleton-shimmer": {
    "terms": {
      "zh": "骨架屏微光",
      "en": "Skeleton Shimmer",
      "aliases": [
        "扫光",
        "流光加载",
        "shimmer effect"
      ],
      "pattern": "Shimmer · Highlight Sweep",
      "principle": "灰底块上叠一层 120% 宽的高光条（transparent→white 45%→transparent），用 background-position 或 transform translateX 从 -100% 扫到 200%；1.4s 循环加随机延迟避免整齐划一。"
    },
    "effectTags": [
      "骨架屏",
      "微光",
      "加载"
    ]
  },
  "text-reveal": {
    "terms": {
      "zh": "文本揭示",
      "en": "Text Reveal / Masked Rise",
      "aliases": [
        "文字上滑",
        "遮罩揭示",
        "逐词入场"
      ],
      "pattern": "Text · Masked Rise-In",
      "principle": "每个词包一层 overflow: hidden 的外框，内层 span 初始 translateY(110%) 藏在遮罩下，keyframes 上滑到 0，用 --i 变量 × 90ms 计算错峰 delay 实现逐词入场。"
    },
    "effectTags": [
      "文本",
      "揭示",
      "遮罩",
      "错峰"
    ]
  },
  "text-rotate": {
    "terms": {
      "zh": "词组轮换",
      "en": "Text Rotate",
      "aliases": [
        "文字轮播",
        "词组切换",
        "rotating words"
      ],
      "pattern": "Text Rotate · Slide Swap",
      "principle": "固定高度裁切容器内叠放所有词组，激活词 translateY(0)、待入词 translateY(110%)、离场词 -110%；切换时交换类名，宽度用测量值内联过渡避免跳动。"
    },
    "effectTags": [
      "词组轮换",
      "循环",
      "hero"
    ]
  },
  "text-scramble": {
    "terms": {
      "zh": "乱码解码",
      "en": "Text Scramble / Decode Effect",
      "aliases": [
        "文字乱码",
        "黑客解码",
        "Matrix Decode"
      ],
      "pattern": "Text · Scramble Decode",
      "principle": "setInterval 每 55ms 一 tick，已过 tick 数一半的字符从左往右锁定为真实内容，其余位置每 tick 从 67 字符乱码池随机取字；空格永不替换，保证布局不跳。"
    },
    "effectTags": [
      "文字",
      "乱码",
      "解码",
      "标题"
    ]
  },
  "typewriter": {
    "terms": {
      "zh": "打字机文字",
      "en": "Typewriter Effect",
      "aliases": [
        "打字效果",
        "逐字输出",
        "Type Loop"
      ],
      "pattern": "Text · Type-Erase Loop",
      "principle": "setTimeout 链驱动状态机：打字 90ms/字、删完停 1600ms 后以 45ms/字回删，slice(0, visible) 截取文本重写 textContent，光标用 steps(1) 关键帧做方块硬切闪烁。"
    },
    "effectTags": [
      "打字机",
      "文字循环",
      "光标",
      "hero"
    ]
  },
  "wave-text": {
    "terms": {
      "zh": "波浪文字",
      "en": "Wave Text",
      "aliases": [
        "逐字浮动",
        "正弦文字",
        "text wave"
      ],
      "pattern": "Wave · Per-char Sine Bounce",
      "principle": "JS 把文本拆成逐字 span，每个 span 跑同一个 translateY 关键帧动画，仅 animation-delay 按索引递增（i × 相位步长），形成正弦波面；色彩交替用 nth-child(odd)。"
    },
    "effectTags": [
      "波浪",
      "逐字",
      "文字动画"
    ]
  },
  "announcement-bar": {
    "terms": {
      "zh": "公告条",
      "en": "Announcement Bar",
      "aliases": [
        "顶部通知条",
        "营销条",
        "announcement"
      ],
      "pattern": "Announcement Bar · Top Banner",
      "principle": "多条公告用横向轨道 translateX 轮播（grid-auto-flow: column），自动播放 setInterval + hover/交互暂停；关闭时量高度过渡归零再 display none，localStorage 记忆后下次直接不渲染。"
    },
    "effectTags": [
      "公告条",
      "轮播",
      "营销"
    ]
  },
  "app-download-cta": {
    "terms": {
      "zh": "应用下载横幅",
      "en": "App Download CTA Banner",
      "aliases": [
        "下载横幅",
        "App 推广条",
        "商店徽章横幅"
      ],
      "pattern": "CTA Section · App Promotion",
      "principle": "深色渐变容器用 grid 分为文案区（商店徽章按钮）与纯 CSS 绘制的手机 mockup 两列，mockup 用嵌套 div 模拟刘海、骨架屏与 FAB，并用 translateY 关键帧做 4.5s 缓慢悬浮。"
    },
    "effectTags": [
      "下载横幅",
      "CTA",
      "手机 mockup",
      "深色",
      "悬浮"
    ]
  },
  "comparison-table": {
    "terms": {
      "zh": "方案对比表",
      "en": "Comparison Table",
      "aliases": [
        "功能对比",
        "定价对比",
        "plan comparison"
      ],
      "pattern": "Comparison · Feature Matrix",
      "principle": "table 三列布局，推荐列用负 margin 拉高 + 描边 + 角标突出；功能项用 ✓ / — 图标替代文字，扫读效率最高；窄屏包一层 overflow-x 容器并在右缘加渐隐投影暗示可横滑。"
    },
    "effectTags": [
      "对比表",
      "定价",
      "落地页"
    ]
  },
  "contact-form-section": {
    "terms": {
      "zh": "联系表单区块",
      "en": "Contact Form Section",
      "aliases": [
        "联系表单",
        "留言表单",
        "咨询表单区块"
      ],
      "pattern": "Contact · Validated Form",
      "principle": "左右分栏卡片：左侧价值介绍、右侧 novalidate 表单由 RULES 映射表驱动校验（blur 失焦即查、已有错误的字段 input 时实时复检），错误通过 aria-invalid + data-err-for 关联的错误段落展示，提交失败聚焦首个出错字段，成功后 form/done 面板互换 hidden。"
    },
    "effectTags": [
      "联系表单",
      "表单校验",
      "无障碍",
      "成功态",
      "转化"
    ]
  },
  "cookie-consent": {
    "terms": {
      "zh": "Cookie 同意条",
      "en": "Cookie Consent Banner",
      "aliases": [
        "隐私同意条",
        "Cookie 弹条",
        "GDPR 同意栏"
      ],
      "pattern": "Consent · Cookie Banner",
      "principle": "fixed 底部居中的白底卡片条，choice 三态（全部接受/仅必要/逐项偏好）序列化进 localStorage，再次访问读到已存选择就静默不弹；偏好面板是逐项开关，必要项用 disabled 锁定，出场用 0.32s 上滑动画、离场先加 leaving 类再隐藏。"
    },
    "effectTags": [
      "Cookie 同意",
      "合规",
      "localStorage",
      "开关",
      "底部浮层"
    ]
  },
  "cta-banner": {
    "terms": {
      "zh": "CTA 横幅",
      "en": "CTA Banner / Call-to-Action Section",
      "aliases": [
        "行动号召横幅",
        "转化横幅",
        "注册横幅"
      ],
      "pattern": "CTA Section · Gradient Banner",
      "principle": "实心版用 120deg 三色渐变打底，独立 ct-bg 层（inset: -30%）叠两层 radial-gradient 光斑并以 14s alternate 动画缓慢漂移制造纵深；浅色变体改为白底描边、flex 两端对齐的横向布局。"
    },
    "effectTags": [
      "CTA",
      "渐变",
      "光斑",
      "行动号召",
      "转化"
    ]
  },
  "faq-accordion": {
    "terms": {
      "zh": "FAQ 手风琴",
      "en": "FAQ Accordion",
      "aliases": [
        "常见问题折叠",
        "问答手风琴",
        "折叠面板"
      ],
      "pattern": "FAQ · Accordion",
      "principle": "用原生 details/summary 保证键盘与语义可访问性，展开动画靠 grid-template-rows 0fr→1fr 过渡（无需 JS 测量高度）；summary 点击被 preventDefault 接管，收起时先跑 is-open 高度动画、transitionend 后再移除 open 属性，同时做单开互斥。"
    },
    "effectTags": [
      "手风琴",
      "折叠",
      "FAQ",
      "无障碍",
      "营销"
    ]
  },
  "features-grid": {
    "terms": {
      "zh": "功能区网格",
      "en": "Features Grid / Feature Cards",
      "aliases": [
        "特性网格",
        "功能卡片",
        "卖点网格"
      ],
      "pattern": "Features · Card Grid",
      "principle": "grid-template-columns: repeat(3, 1fr) 的等宽三列卡片网格，每卡为图标方块 + 标题 + 说明的纵向结构，hover 时上浮 3px 并把描边过渡到品牌主色。"
    },
    "effectTags": [
      "功能网格",
      "卡片",
      "卖点",
      "hover 上浮",
      "营销"
    ]
  },
  "footer-minimal": {
    "terms": {
      "zh": "页脚区块",
      "en": "Footer Section / Minimal Footer",
      "aliases": [
        "站点页脚",
        "底部导航",
        "版权栏页脚"
      ],
      "pattern": "Footer · Site Navigation",
      "principle": "圆角卡片式页脚：grid 1.2fr/2fr 分为品牌列（logo + 简介 + 28px 方形社交图标）与三列链接导航，下方 border-top 分隔的版权底栏 flex 两端对齐；深色变体只覆盖颜色变量不改结构，560px 以下主区改单列、链接列降两列。"
    },
    "effectTags": [
      "页脚",
      "导航",
      "版权栏",
      "深色变体",
      "站点结构"
    ]
  },
  "hero-centered": {
    "terms": {
      "zh": "居中 Hero",
      "en": "Centered Hero Section",
      "aliases": [
        "首屏横幅",
        "居中头图",
        "落地页 Hero"
      ],
      "pattern": "Hero · Landing Above the Fold",
      "principle": "min-height: 100vh 的 flex 纵向居中容器，内容按徽章 → 大标题 → 副标题 → 双按钮 → 信任文案的纵向节奏堆叠，背景用单个 radial-gradient 在顶部打一圈品牌色光晕。"
    },
    "effectTags": [
      "首屏",
      "Hero",
      "落地页",
      "居中布局",
      "营销"
    ]
  },
  "hero-split": {
    "terms": {
      "zh": "分栏 Hero",
      "en": "Split Hero",
      "aliases": [
        "Left-Right Hero",
        "Two-Column Hero",
        "图文首屏"
      ],
      "pattern": "Conversion Landing · Above the Fold",
      "principle": "左栏用眉题、标题、卖点与 CTA 完成价值主张，右栏展示产品界面示意——文字负责说服，视觉负责证明，两侧在同一首屏完成分工。"
    },
    "effectTags": [
      "首屏",
      "分栏",
      "落地页",
      "营销"
    ]
  },
  "how-it-works": {
    "terms": {
      "zh": "步骤流程区块",
      "en": "How It Works",
      "aliases": [
        "三步流程",
        "流程说明",
        "steps section"
      ],
      "pattern": "Steps · Numbered Flow",
      "principle": "三列 grid 布局，步骤间用横贯的虚线连接（伪元素画在列间隙）；大号半透明步骤数字压在图标后面制造层次；窄屏切单列后连接线改纵向或隐藏。"
    },
    "effectTags": [
      "步骤流程",
      "落地页",
      "引导"
    ]
  },
  "integrations-grid": {
    "terms": {
      "zh": "集成应用网格",
      "en": "Integrations Grid",
      "aliases": [
        "应用矩阵",
        "生态网格",
        "integrations"
      ],
      "pattern": "Integrations · Logo Tile Grid",
      "principle": "grid auto-fill minmax(150px,1fr) 瓷砖布局，每块 = 44px 字标色块（品牌色 12% 底 + 品牌色字母）+ 名称 + 一句话描述；「已接入」小绿点标签区分状态；悬停 translateY(-3px) + 边框亮主色。"
    },
    "effectTags": [
      "集成",
      "网格",
      "落地页"
    ]
  },
  "logo-cloud": {
    "terms": {
      "zh": "Logo 墙区块",
      "en": "Logo Cloud / Logo Marquee",
      "aliases": [
        "客户 Logo 墙",
        "合作伙伴墙",
        "无缝滚动 Logo"
      ],
      "pattern": "Social Proof · Logo Cloud",
      "principle": "静态形态是 3 列网格卡片 + 悬停变色上浮；滚动形态把同一组 logo 复制两份放进 width: max-content 的 flex 轨道，translateX(-50% - gap/2) 平移恰好一份副本宽度实现无缝循环，两侧用 mask-image 渐隐，hover 时 animation-play-state: paused。"
    },
    "effectTags": [
      "Logo 墙",
      "无缝滚动",
      "社会证明",
      "跑马灯",
      "信任背书"
    ]
  },
  "newsletter-cta": {
    "terms": {
      "zh": "订阅区块",
      "en": "Newsletter CTA / Email Subscribe Block",
      "aliases": [
        "邮件订阅框",
        "Newsletter 表单",
        "邮箱收集区块"
      ],
      "pattern": "Conversion · Newsletter Signup",
      "principle": "白底圆角卡片内放徽章 + 标题 + 说明 + 邮箱输入框/按钮组合；提交时用正则 /^[^\\s@]+@[^\\s@]+\\.[^\\s@]{2,}$/ 前端校验，非法则输入框 is-error 描红并 focus，合法则提示语切换 is-ok、表单重放 nl-settle 进场动画并清空输入。"
    },
    "effectTags": [
      "订阅",
      "表单校验",
      "转化",
      "成功态",
      "营销"
    ]
  },
  "pricing-table": {
    "terms": {
      "zh": "定价表",
      "en": "Pricing Table / Pricing Cards",
      "aliases": [
        "价格方案",
        "套餐对比",
        "定价卡片"
      ],
      "pattern": "Pricing · Plan Comparison",
      "principle": "三档卡片用 repeat(3, minmax(0, 280px)) 网格排布；价格数据写在 data-month/data-year 属性上，切换计费周期时 JS 只做文本搬运并用 160ms 淡出淡入掩盖数字跳变；推荐档用双描边（border + 0 0 0 1px box-shadow）与顶部悬浮徽章突出。"
    },
    "effectTags": [
      "定价",
      "方案对比",
      "计费切换",
      "营销",
      "CTA"
    ]
  },
  "stats-bar": {
    "terms": {
      "zh": "数据统计条",
      "en": "Stats Bar / KPI Stats Section",
      "aliases": [
        "数据条",
        "指标条",
        "KPI 展示"
      ],
      "pattern": "Stats · KPI Display",
      "principle": "三种形态共用 dl 语义结构：分隔线条式用 grid-auto-flow: column 等分 + 相邻兄弟选择器画竖线（首项不画），数字统一 tabular-nums 等宽对齐；卡片形态用 4 列网格 + CSS border 三角画涨跌箭头；窄屏改两列并用 nth-child 规则重排竖线。"
    },
    "effectTags": [
      "数据统计",
      "KPI",
      "涨跌指标",
      "等宽数字",
      "仪表盘"
    ]
  },
  "team-section": {
    "terms": {
      "zh": "团队介绍区块",
      "en": "Team Section / Team Grid",
      "aliases": [
        "成员卡片",
        "团队网格",
        "About 团队"
      ],
      "pattern": "About · Team Grid",
      "principle": "四列成员卡网格，每卡为渐变单字圆形头像 + 姓名 + 职位 + 链接胶囊的居中纵向结构；头像用四组 135deg 双色 linear-gradient 变体区分，hover 时卡片上浮且描边过渡到浅青色。"
    },
    "effectTags": [
      "团队",
      "成员卡",
      "渐变头像",
      "About",
      "营销"
    ]
  },
  "testimonial-wall": {
    "terms": {
      "zh": "推荐语墙",
      "en": "Testimonial Wall / Masonry Quotes",
      "aliases": [
        "用户评价墙",
        "瀑布流推荐语",
        "口碑墙"
      ],
      "pattern": "Social Proof · Masonry Layout",
      "principle": "用 CSS multi-column（columns: 3）把不同高度的引用卡片按列瀑布流排布，卡片设 break-inside: avoid 防止被截断，头像用 hsl(var(--avatar-hue)) 按色相变量着色。"
    },
    "effectTags": [
      "瀑布流",
      "推荐语",
      "社会证明",
      "卡片",
      "营销"
    ]
  },
  "trust-badges": {
    "terms": {
      "zh": "信任徽标行",
      "en": "Trust Badges",
      "aliases": [
        "信任背书",
        "认证徽章行",
        "trust seals"
      ],
      "pattern": "Trust · Assurance Row",
      "principle": "横排 3-4 枚徽标卡（图标圆片 + 标题 + 一句话），图标统一线性风格弱化差异、强调语义；区块常置于定价或注册区附近降低决策焦虑。"
    },
    "effectTags": [
      "信任",
      "背书",
      "合规"
    ]
  },
  "border-draw-button": {
    "terms": {
      "zh": "描边绘制按钮",
      "en": "Border Draw Button",
      "aliases": [
        "描边动画按钮",
        "画框按钮",
        "SVG Border Draw"
      ],
      "pattern": "Micro-interaction · SVG Stroke Draw",
      "principle": "按钮上叠一个全尺寸 SVG rect，pathLength=100 把周长归一化，hover 时 stroke-dashoffset 从 100 过渡到 0，描边像画笔一样绕一圈画出边框。"
    },
    "effectTags": [
      "描边",
      "绘制",
      "悬停",
      "SVG",
      "纯 CSS"
    ]
  },
  "hold-to-confirm": {
    "terms": {
      "zh": "长按确认按钮",
      "en": "Hold-to-Confirm Button",
      "aliases": [
        "长按删除",
        "按住确认",
        "Press-and-Hold"
      ],
      "pattern": "Danger Confirmation · Hold-to-Arm",
      "principle": "pointerdown 起用 rAF 按真实时间把 SVG 环形进度从 0 推到 1000ms 满，提前松开立即取消归零，充满才触发危险操作，键盘按住 Space/Enter 等价。"
    },
    "effectTags": [
      "长按",
      "确认",
      "危险操作",
      "防误触",
      "SVG 进度环"
    ]
  },
  "liquid-button": {
    "terms": {
      "zh": "液态填充按钮",
      "en": "Liquid Fill Button",
      "aliases": [
        "Wave Button",
        "Blob Fill Button",
        "Water Fill Button",
        "波纹按钮"
      ],
      "pattern": "Micro-interaction · Hover Fill",
      "principle": "用一个带不规则圆角（42%）的旋转色块作为填充层，hover 时整块从按钮底部上移覆盖；圆角的不规则自转让上升边缘呈现水波晃动感。"
    },
    "effectTags": [
      "填充",
      "悬停",
      "液态",
      "微交互"
    ]
  },
  "loading-button": {
    "terms": {
      "zh": "加载状态按钮",
      "en": "Loading / Async Button",
      "aliases": [
        "异步按钮",
        "提交按钮",
        "Loading Button"
      ],
      "pattern": "Button State Machine · idle → loading → success → idle",
      "principle": "data-state 驱动四种状态切换：loading 时显示 0.7s 线性旋转圈，成功时变绿弹出打勾动画，1.6s 后自动复位，期间按钮保持 disabled。"
    },
    "effectTags": [
      "按钮",
      "加载",
      "异步",
      "状态机",
      "打勾"
    ]
  },
  "magnetic-button": {
    "terms": {
      "zh": "磁性按钮",
      "en": "Magnetic Button",
      "aliases": [
        "磁吸按钮",
        "光标吸附按钮",
        "Magnetic Hover"
      ],
      "pattern": "Micro-interaction · Cursor Magnetism",
      "principle": "mousemove 时算出光标相对按钮中心的偏移，按钮按系数 0.35 平移、内部标签按 0.55 平移形成视差，离开时清空 transform 靠 transition 弹回。"
    },
    "effectTags": [
      "磁性",
      "光标跟随",
      "微交互",
      "视差",
      "按钮"
    ]
  },
  "ripple-button": {
    "terms": {
      "zh": "涟漪按钮",
      "en": "Ripple Button",
      "aliases": [
        "波纹按钮",
        "Material 涟漪",
        "Touch Ripple"
      ],
      "pattern": "Material Design · Ripple",
      "principle": "pointerdown 时在点击坐标创建一个直径 = max(宽,高)×2 的圆形 span，CSS 动画从 scale(0) 扩到 scale(1) 同时淡出，animationend 后移除节点。"
    },
    "effectTags": [
      "涟漪",
      "点击反馈",
      "Material",
      "按钮",
      "扩散"
    ]
  },
  "split-button": {
    "terms": {
      "zh": "分裂按钮",
      "en": "Split Button",
      "aliases": [
        "复合按钮",
        "主次操作按钮",
        "split dropdown"
      ],
      "pattern": "Split Button · Primary + Menu",
      "principle": "一个圆角容器切两半：左半是主操作按钮，右半 32px 箭头区独立 button 控制下拉；中间 1px 半透明分隔线；下拉用与 popover 相同的点外关闭 + Esc 归还焦点模式。"
    },
    "effectTags": [
      "分裂按钮",
      "下拉",
      "工具栏"
    ]
  },
  "article-card": {
    "terms": {
      "zh": "文章卡",
      "en": "Article Card",
      "aliases": [
        "博客卡片",
        "内容卡片",
        "post card"
      ],
      "pattern": "Article Card · Editorial Listing",
      "principle": "无图编辑风：顶部 3px 分类色条承担视觉识别，层级靠字号与灰度对比（标题 16 深灰 / 摘要 13 中灰 / 元信息 12 浅灰）；作者用首字字标小方块，避免头像依赖。"
    },
    "effectTags": [
      "文章卡",
      "博客",
      "排版"
    ]
  },
  "code-snippet-card": {
    "terms": {
      "zh": "代码片段卡",
      "en": "Code Snippet Card",
      "aliases": [
        "Tabbed Code Block",
        "代码展示卡",
        "复制代码卡"
      ],
      "pattern": "Tabs · Clipboard",
      "principle": "role=tablist 三标签点击切换并同步 aria-selected，用 innerHTML 渲染预置高亮片段；复制取 code 的 textContent，优先 navigator.clipboard，非安全上下文降级隐藏 textarea + execCommand。"
    },
    "effectTags": [
      "代码",
      "标签页",
      "复制",
      "深色",
      "高亮"
    ]
  },
  "course-card": {
    "terms": {
      "zh": "课程卡",
      "en": "Course Card",
      "aliases": [
        "网课卡片",
        "教育卡片",
        "course listing"
      ],
      "pattern": "Course Card · Media Listing",
      "principle": "上图下文媒体卡结构；封面用渐变 + 大字标识代替图片资源；学习进度条用嵌套 div 宽度百分比渲染；价格行由现价（强调色加粗）+ 划线原价组成对比锚点。"
    },
    "effectTags": [
      "课程卡",
      "教育",
      "进度"
    ]
  },
  "donut-chart": {
    "terms": {
      "zh": "环形占比卡",
      "en": "Donut Chart Card",
      "aliases": [
        "环形图",
        "甜甜圈图",
        "Donut Chart"
      ],
      "pattern": "Data Visualization · Donut Chart",
      "principle": "每段用 SVG circle 的 pathLength=100 归一化，stroke-dasharray 前段写占比、后段写剩余，stroke-dashoffset 按前序占比累计偏移，加载时延迟依次从 0 生长。"
    },
    "effectTags": [
      "环形图",
      "数据可视化",
      "占比",
      "生长动画"
    ]
  },
  "expandable-card": {
    "terms": {
      "zh": "展开卡片",
      "en": "Expandable Card",
      "aliases": [
        "折叠卡片",
        "手风琴卡",
        "展开详情卡"
      ],
      "pattern": "Expand / Collapse · Grid Rows Animation",
      "principle": "外层 grid-template-rows: 0fr → 1fr 过渡 0.32s cubic-bezier(0.22,1,0.36,1)，内层 overflow:hidden + min-height:0，内容高度变化无需 JS 测量即可平滑展开；JS 只切换 data-open 与 aria-expanded。"
    },
    "effectTags": [
      "展开",
      "折叠",
      "高度过渡",
      "grid-rows"
    ]
  },
  "file-card": {
    "terms": {
      "zh": "文件卡",
      "en": "File Card",
      "aliases": [
        "附件卡",
        "文件列表项",
        "attachment card"
      ],
      "pattern": "File Card · Attachment Row",
      "principle": "类型图标色块按扩展名映射色系（PDF 红 / 图表绿 / 表格青…），图标直接用扩展名文字比通用图标更直观；上传中态由「进度条 + 百分比」替换元信息行，完成后淡出切换。"
    },
    "effectTags": [
      "文件",
      "附件",
      "上传"
    ]
  },
  "flight-card": {
    "terms": {
      "zh": "航班卡",
      "en": "Flight Card",
      "aliases": [
        "机票卡",
        "航班信息",
        "flight ticket"
      ],
      "pattern": "Flight · Route Summary",
      "principle": "三段式：左机场代码（出发）、中间航线图（起终点圆点 + 虚线 + 飞机图标 + 下方时长）、右机场代码（到达）；代码用 24px 大字，城市全称小字补充；底部行放航司/舱位与价格按钮。"
    },
    "effectTags": [
      "航班",
      "旅行",
      "路径图"
    ]
  },
  "glass-card": {
    "terms": {
      "zh": "玻璃卡片",
      "en": "Glass Card",
      "aliases": [
        "玻璃拟态卡",
        "磨砂卡片",
        "Glassmorphism 卡"
      ],
      "pattern": "Glassmorphism",
      "principle": "卡面 rgba(255,255,255,0.62) 半透明白 + backdrop-filter: blur(18px) saturate(1.4) 折射背后三个 blur(60px) 的 teal/indigo/pink 极光色斑（26s–38s 缓慢漂移），再叠 1px 白描边与 inset 顶部高光构成玻璃层次。"
    },
    "effectTags": [
      "玻璃拟态",
      "backdrop-filter",
      "极光",
      "磨砂",
      "纯 CSS"
    ]
  },
  "image-comparison": {
    "terms": {
      "zh": "图片对比滑块",
      "en": "Image Comparison Slider",
      "aliases": [
        "Before/After 滑块",
        "图像对比卡",
        "对比分割滑块"
      ],
      "pattern": "Clip-path Comparison",
      "principle": "上层（Before）用 clip-path: inset(0 (100-pos)% 0 0) 按百分比裁切；容器任意处 pointerdown 跳转、手柄拖拽走 setPointerCapture 跟手；键盘方向键 ±2 / PageUp ±10 / Home/End 跳转并同步 aria-valuenow。"
    },
    "effectTags": [
      "对比滑块",
      "clip-path",
      "拖拽",
      "before-after"
    ]
  },
  "invoice-card": {
    "terms": {
      "zh": "发票卡",
      "en": "Invoice Card",
      "aliases": [
        "账单卡",
        "付款卡",
        "invoice item"
      ],
      "pattern": "Invoice · Billing Row",
      "principle": "上下两层：上层发票号 + 状态徽章 + 金额；下层到期日与操作按钮；状态徽章三色系（已付绿 / 待付琥珀 / 逾期红）；明细行用 grid-rows 0fr→1fr 展开，箭头旋转。"
    },
    "effectTags": [
      "发票",
      "账单",
      "状态"
    ]
  },
  "job-card": {
    "terms": {
      "zh": "职位卡",
      "en": "Job Card",
      "aliases": [
        "招聘卡片",
        "职位列表项",
        "job listing card"
      ],
      "pattern": "Job Card · Listing Item",
      "principle": "左徽标右内容的两栏网格；薪资用强调色加粗形成视觉锚点；悬停抬升由 translateY(-2px) + 阴影加深完成；收藏按钮切换填充态并同步 aria-pressed。"
    },
    "effectTags": [
      "职位卡",
      "列表",
      "悬停"
    ]
  },
  "music-player-card": {
    "terms": {
      "zh": "音乐播放器卡",
      "en": "Music Player Card",
      "aliases": [
        "播放器卡片",
        "黑胶播放器",
        "MP3 卡片"
      ],
      "pattern": "Media Player · Vinyl Spin",
      "principle": "rAF 循环用真实帧间隔 dt 累加播放位置（切后台回来不跳变），进度条 pointerdown 捕获拖拽 seek 且拖拽期间暂停推进；黑胶用 repeating-radial-gradient 画纹路，默认 paused、播放时才恢复 6s 旋转。"
    },
    "effectTags": [
      "播放器",
      "黑胶",
      "进度条",
      "rAF 计时"
    ]
  },
  "notification-card": {
    "terms": {
      "zh": "通知卡",
      "en": "Notification Card",
      "aliases": [
        "消息卡",
        "通知列表",
        "notification item"
      ],
      "pattern": "Notification · Feed Item",
      "principle": "左侧类型图标（底色 = 类型色 10% 透明）+ 内容区 + 相对时间；未读状态用标题加粗 + 右上蓝点表达；「全部已读」按钮移除所有未读点并把粗体转常规，未读数徽标同步归零。"
    },
    "effectTags": [
      "通知",
      "消息",
      "列表"
    ]
  },
  "order-tracking-card": {
    "terms": {
      "zh": "订单跟踪卡",
      "en": "Order Tracking Card",
      "aliases": [
        "物流卡片",
        "快递跟踪卡",
        "步骤条卡片"
      ],
      "pattern": "Stepper + Timeline",
      "principle": "四等分 flex 步条叠在 ::before 贯穿底轨上，完成节点用内嵌 SVG data-URI 白色对勾，当前节点 box-shadow 1.8s 脉冲；下方日志用 li::before 圆点 + ::after 竖线串成时间线，纯数据渲染无状态逻辑。"
    },
    "effectTags": [
      "步骤条",
      "时间线",
      "物流",
      "状态",
      "脉冲"
    ]
  },
  "podcast-card": {
    "terms": {
      "zh": "播客卡",
      "en": "Podcast Card",
      "aliases": [
        "单集卡",
        "音频卡",
        "episode card"
      ],
      "pattern": "Podcast · Episode Player Row",
      "principle": "左封面右信息的横向卡；播放按钮在播放/暂停双态间切换（SVG 交替显示），进度条由 rAF 按剩余时间推进（演示用模拟），倍速按钮循环 1x→1.25x→1.5x→2x。"
    },
    "effectTags": [
      "播客",
      "播放",
      "进度"
    ]
  },
  "product-card": {
    "terms": {
      "zh": "商品卡片",
      "en": "Product Card",
      "aliases": [
        "电商卡片",
        "购物卡片",
        "商品展示卡"
      ],
      "pattern": "E-commerce Card",
      "principle": "商品视觉用双层 linear-gradient 形状加内/外阴影冒充产品图；尺码组以 aria-checked 单选语义切换；加购按钮点击后换色显示 \"Added ✓\"，1400ms 定时复原，连点靠 clearTimeout 防抖。"
    },
    "effectTags": [
      "电商",
      "加购",
      "尺码选择",
      "悬浮",
      "评分"
    ]
  },
  "profile-card": {
    "terms": {
      "zh": "个人资料卡片",
      "en": "Profile Card",
      "aliases": [
        "团队卡片",
        "头像卡",
        "团队成员卡"
      ],
      "pattern": "Profile · Follow Toggle",
      "principle": "头像环用 conic-gradient 外层 + 3px padding 挖环、内层 3px 白 border 盖出环宽；关注按钮以 aria-pressed 为唯一状态源驱动样式切换，并同步解析/增减粉丝计数。"
    },
    "effectTags": [
      "头像",
      "渐变环",
      "关注按钮",
      "资料"
    ]
  },
  "shared-layout-gallery": {
    "terms": {
      "zh": "共享布局画廊",
      "en": "Shared Layout Gallery",
      "aliases": [
        "FLIP 过渡",
        "共享元素动画",
        "展开详情画廊"
      ],
      "pattern": "Shared Element Transition · FLIP",
      "principle": "点击卡片时克隆其视觉层为 fixed 飞行元素摆到详情终点位，再用 WAAPI 反向施加 First-Inverted 位移/缩放补间（560ms），动画结束移除克隆；关闭沿原路径反向播放，配焦点圈闭与 animating 锁。"
    },
    "effectTags": [
      "FLIP",
      "共享元素",
      "展开",
      "画廊",
      "布局动画"
    ]
  },
  "sparkline-chart": {
    "terms": {
      "zh": "迷你走势卡",
      "en": "Sparkline Chart",
      "aliases": [
        "迷你图",
        "KPI 走势卡",
        "微型图表"
      ],
      "pattern": "Sparkline · Data Visualization",
      "principle": "JS 把数据按 min/max 归一化映射进 200×64 viewBox（四周 PAD 6）生成 SVG 折线 path + 闭合渐变面积，柱状形态用按最大值归一的百分比高度 flex 条；描边生长靠 stroke-dasharray/offset 动画。"
    },
    "effectTags": [
      "sparkline",
      "数据可视化",
      "走势",
      "描边动画",
      "涨红跌绿"
    ]
  },
  "spotlight-card": {
    "terms": {
      "zh": "聚光卡片",
      "en": "Spotlight Card",
      "aliases": [
        "边框辉光卡",
        "光标跟随卡片",
        "Linear 风格卡片"
      ],
      "pattern": "Spotlight Border · Cursor Tracking",
      "principle": "网格容器上做一次 pointermove 事件委托，把光标坐标写入每张卡的 --spot-x/--spot-y；::before 用 radial-gradient 240px circle 在该点画辉光（hover 才淡入），卡片本体用 1px padding + ::after 内衬白面做出渐变描边三明治。"
    },
    "effectTags": [
      "聚光",
      "辉光",
      "光标跟随",
      "边框"
    ]
  },
  "stats-card": {
    "terms": {
      "zh": "KPI 数据卡",
      "en": "KPI Stats Card",
      "aliases": [
        "数据卡",
        "指标卡",
        "涨跌卡片"
      ],
      "pattern": "KPI · Sparkline",
      "principle": "纯 CSS + 静态 SVG：走势线用 stroke-dasharray 300 → dashoffset 0 的 1.1s 描边生长动画，涨红 #dc2626 / 跌绿 #16a34a 两个 CSS 变量同时驱动徽章配色与线色，另有无走势线的紧凑变体。"
    },
    "effectTags": [
      "KPI",
      "涨跌",
      "走势线",
      "仪表盘",
      "描边动画"
    ]
  },
  "tilt-card": {
    "terms": {
      "zh": "3D 倾斜卡片",
      "en": "3D Tilt Card",
      "aliases": [
        "Tilt 卡",
        "视差倾斜卡",
        "光标 3D 卡"
      ],
      "pattern": "3D Tilt · Cursor Tracking",
      "principle": "pointermove 把指针位置归一化到 0–1，映射为 ±MAX_TILT(10°) 的 rotateX/rotateY 直接写 style.transform；内容层 translateZ(28px) 拉出层次，眩光坐标写 --glare-x/y 由 radial-gradient 呈现；hover:none 设备直接跳过。"
    },
    "effectTags": [
      "3D",
      "倾斜",
      "视差",
      "光标跟随",
      "眩光"
    ]
  },
  "wallet-card": {
    "terms": {
      "zh": "钱包卡",
      "en": "Wallet Card",
      "aliases": [
        "余额卡",
        "资产卡",
        "balance card"
      ],
      "pattern": "Wallet · Balance Hero",
      "principle": "深色渐变卡面（多径向光斑叠加制造质感），余额数字用 rAF 缓动从 0 滚动到目标值；卡号默认 6222 •••• •••• 1234 遮罩，眼睛图标切换显示真实卡号。"
    },
    "effectTags": [
      "钱包",
      "余额",
      "数字动画"
    ]
  },
  "weather-card": {
    "terms": {
      "zh": "天气卡片",
      "en": "Weather Card",
      "aliases": [
        "天气组件",
        "预报卡",
        "CSS 天气场景"
      ],
      "pattern": "CSS Illustration · Ambient Animation",
      "principle": "165deg 三段天空渐变当天幕，太阳（radial-gradient 圆 + 光晕）、云（胶囊 + ::before/::after 圆形叠加）、雨滴（3×11px 圆角条）全由 CSS 绘制，keyframes 分别做呼吸 / 漂移 / 下落循环，JS 只负责渲染逐小时与五日数据。"
    },
    "effectTags": [
      "CSS 绘图",
      "天气",
      "动效场景",
      "渐变",
      "零图片"
    ]
  },
  "auto-textarea": {
    "terms": {
      "zh": "自适应文本域",
      "en": "Auto-Growing Textarea",
      "aliases": [
        "自动增高文本域",
        "自增高 textarea",
        "Autosize Textarea"
      ],
      "pattern": "Textarea · Autosize",
      "principle": "input 时先把 height 置回 auto 让内容自然收缩，再读 scrollHeight 取 min(scrollHeight, maxHeight) 赋回，高度因此可增可减；超过 maxHeight 后加 is-overflow 切换内部滚动。"
    },
    "effectTags": [
      "自动增高",
      "文本域",
      "字数统计",
      "表单"
    ]
  },
  "color-picker": {
    "terms": {
      "zh": "色板选择器",
      "en": "Color Swatch Picker",
      "aliases": [
        "预设色板",
        "swatch 选择器",
        "Preset Color Picker"
      ],
      "pattern": "Color Picker · Radio Group",
      "principle": "色块是 role=radio 的 button：选中即 aria-checked + tabIndex 收敛为单一 tab stop；方向键按 (i±1+8)%8 循环移动并选中；选中色的 data-hex 写入根节点 --cl-live CSS 变量，预览区与示例按钮/徽章随之联动。"
    },
    "effectTags": [
      "取色",
      "色板",
      "radiogroup",
      "主题联动",
      "表单"
    ]
  },
  "combobox-autocomplete": {
    "terms": {
      "zh": "自动补全输入",
      "en": "Combobox / Autocomplete",
      "aliases": [
        "联想输入",
        "下拉建议",
        "autocomplete"
      ],
      "pattern": "Combobox · Filter-as-type",
      "principle": "input 事件里过滤数据源渲染下拉项；ARIA 组合框模式：input 为 combobox 角色、下拉为 listbox、选项为 option 并用 aria-activedescendant 追踪高亮；↑↓ 移动、Enter 选中、Esc 关闭。"
    },
    "effectTags": [
      "自动补全",
      "下拉",
      "键盘导航"
    ]
  },
  "currency-input": {
    "terms": {
      "zh": "金额输入框",
      "en": "Currency Input",
      "aliases": [
        "千分位输入",
        "金额格式化",
        "money input"
      ],
      "pattern": "Currency · Formatted Numeric Input",
      "principle": "input 监听里剥离非数字字符、限制一位小数点与两位小数，再把整数部分按千分位重插逗号；真正的数值存 data-value，显示与存储分离避免格式化干扰光标。"
    },
    "effectTags": [
      "金额",
      "格式化",
      "表单"
    ]
  },
  "date-picker": {
    "terms": {
      "zh": "日期选择器",
      "en": "Date Picker",
      "aliases": [
        "月历",
        "日历选择",
        "Calendar Picker"
      ],
      "pattern": "Date Picker · Month Grid",
      "principle": "周一起始换算首列偏移 ((getDay()+6)%7)，从本月 1 号往前补位渲染 42 格；非本月日期 disabled 置灰，今天 inset 描边、选中实心；视图月份存 Date 对象，setMonth ±1 切换后整格重建。"
    },
    "effectTags": [
      "日期选择",
      "月历",
      "本地化",
      "表单"
    ]
  },
  "emoji-picker": {
    "terms": {
      "zh": "表情选择器",
      "en": "Emoji Picker",
      "aliases": [
        "表情面板",
        "emoji 面板",
        "Emoji Selector"
      ],
      "pattern": "Picker · Tabbed Grid",
      "principle": "分类数据（id/icon/label/items）驱动 tablist + listbox 渲染：分类按钮切换 activeCat 后重建网格；搜索框有值时跨全部分类 flatMap 合并过滤；选中后去重插入最近使用数组头部并 slice(0, 8) 截断。"
    },
    "effectTags": [
      "表情",
      "分类切换",
      "搜索",
      "最近使用",
      "选择器"
    ]
  },
  "file-upload": {
    "terms": {
      "zh": "拖拽上传",
      "en": "Drag & Drop Upload",
      "aliases": [
        "拖放上传区",
        "文件上传",
        "Dropzone"
      ],
      "pattern": "File Upload · Dropzone",
      "principle": "dropzone 监听 dragenter/dragover/dragleave/drop 并全部 preventDefault，用 data-dragover 属性驱动高亮；drop 的 dataTransfer.files 与 input change 的 files 走同一个 addFile：超 10MB 跳过，逐文件 setInterval 模拟进度，× 移除时先 clearInterval 再移除节点。"
    },
    "effectTags": [
      "上传",
      "拖拽",
      "文件列表",
      "进度条",
      "表单"
    ]
  },
  "floating-label-input": {
    "terms": {
      "zh": "浮动标签输入框",
      "en": "Floating Label Input",
      "aliases": [
        "Material 输入框",
        "悬浮标签输入框",
        "Floating Label"
      ],
      "pattern": "Floating Label · CSS-only",
      "principle": "label 绝对定位在输入框垂直居中，用 input:focus + .fl-label 与 :not(:placeholder-shown) + .fl-label 两条相邻选择器把标签上浮到顶部（top 0、字号 14→11px）；placeholder 留一个空格充当'是否已填'的状态开关，全程零 JS。"
    },
    "effectTags": [
      "浮动标签",
      "Material",
      "纯 CSS",
      "表单"
    ]
  },
  "inline-edit": {
    "terms": {
      "zh": "行内编辑",
      "en": "Inline Edit",
      "aliases": [
        "原地编辑",
        "点击编辑",
        "click to edit"
      ],
      "pattern": "Inline Edit · Contenteditable-free Swap",
      "principle": "静态文本与 input 互相切换显示；进入编辑时把 input 宽度设为文本渲染宽度避免跳动，Enter/失焦提交、Esc 还原；role 由按钮与 textbox 分担保证读屏可用。"
    },
    "effectTags": [
      "行内编辑",
      "表单",
      "交互"
    ]
  },
  "mention-input": {
    "terms": {
      "zh": "@提及输入框",
      "en": "Mention Input",
      "aliases": [
        "提及输入",
        "@提及",
        "Autocomplete Mention"
      ],
      "pattern": "Mention · Autocomplete Trigger",
      "principle": "contenteditable 的 input 事件里用正则 /@([^\\s@]{0,12})$/ 匹配光标前文本唤起候选菜单；选中后把 @词文本替换为 contentEditable=false 的标签节点，并手动重建 Range 把光标落到标签后。"
    },
    "effectTags": [
      "提及",
      "自动补全",
      "富文本",
      "contenteditable",
      "输入"
    ]
  },
  "multi-select": {
    "terms": {
      "zh": "多选下拉",
      "en": "Multi-Select Dropdown",
      "aliases": [
        "多选选择器",
        "chips 多选",
        "Multi Select"
      ],
      "pattern": "Multi-Select · Combobox with Chips",
      "principle": "选中项存入 Set：触发框里 chips 与占位符二选一显示；面板按 Set 同步每个选项的 aria-selected，搜索 input 过滤重建列表；ESC 或面板外 pointerdown 关闭并把焦点还给触发框。"
    },
    "effectTags": [
      "多选",
      "下拉",
      "chips",
      "搜索过滤",
      "表单"
    ]
  },
  "multi-step-form": {
    "terms": {
      "zh": "多步骤表单",
      "en": "Multi-Step Form",
      "aliases": [
        "分步表单",
        "向导表单",
        "Wizard Form"
      ],
      "pattern": "Wizard · Stepped Form",
      "principle": "每步一个 section[hidden] 切换；Continue 时只对当前步的 input/select 跑 checkValidity，错误写入 data-error-for 段落并标 aria-invalid；切换方向参数决定 slide 动画从左还是右入场，最后一步用 FormData 生成 dt/dd 回显清单。"
    },
    "effectTags": [
      "多步骤",
      "分步校验",
      "向导",
      "表单"
    ]
  },
  "otp-input": {
    "terms": {
      "zh": "验证码输入",
      "en": "OTP Input",
      "aliases": [
        "一次性密码输入",
        "验证码格子",
        "One-Time Password Input"
      ],
      "pattern": "OTP Input · Segmented Input",
      "principle": "6 个 maxlength=1 的独立 input 组成格子：input 时只保留末位数字并自动前进焦点，Backspace 在本格为空时回退清空前格，paste 事件拦截后把数字逐格分发，全满后 500ms 定时器模拟校验。"
    },
    "effectTags": [
      "验证码",
      "分格输入",
      "粘贴分发",
      "表单"
    ]
  },
  "password-strength": {
    "terms": {
      "zh": "密码强度输入",
      "en": "Password Strength Input",
      "aliases": [
        "密码强度计",
        "密码校验表单",
        "Password Meter"
      ],
      "pattern": "Form Validation · Strength Meter",
      "principle": "input 事件里跑 4 条规则（长度≥12、同时含大小写、含数字、含符号），通过数 n 映射为强度条宽度 n/4×100% 与 4 级颜色文案，规则清单逐项用 data-met 驱动打勾。"
    },
    "effectTags": [
      "密码",
      "强度条",
      "实时校验",
      "表单"
    ]
  },
  "range-slider": {
    "terms": {
      "zh": "区间滑块",
      "en": "Range Slider",
      "aliases": [
        "双端滑块",
        "价格区间选择",
        "Dual Range Slider"
      ],
      "pattern": "Slider · Pointer Events Drag",
      "principle": "拇指是绝对定位的 button[role=slider]：pointerdown 用 setPointerCapture 锁定指针，pointermove 把 clientX 反算成轨道数值，先按 step 四舍五入吸附再 clamp；双端实例互设 peer，clamp 时保证两端至少差一个 step。"
    },
    "effectTags": [
      "滑块",
      "拖拽",
      "区间选择",
      "步进",
      "键盘可达"
    ]
  },
  "search-input": {
    "terms": {
      "zh": "搜索输入框",
      "en": "Search Input with Suggestions",
      "aliases": [
        "搜索联想框",
        "搜索框",
        "Search Autocomplete"
      ],
      "pattern": "Search · Debounced Combobox",
      "principle": "input 经 180ms 防抖后按 label + keywords 过滤本地数据，结果先 escapeHtml 再把匹配片段包 <mark> 高亮渲染为 role=option；↑↓ 移动 activeIndex、Enter 选中、Esc 关闭，外点关闭，清空按钮随输入显隐。"
    },
    "effectTags": [
      "搜索",
      "防抖",
      "联想",
      "键盘导航",
      "表单"
    ]
  },
  "stepper-input": {
    "terms": {
      "zh": "数量步进器",
      "en": "Stepper Input",
      "aliases": [
        "数量选择器",
        "加减器",
        "Quantity Stepper"
      ],
      "pattern": "Stepper · Long-press Repeat",
      "principle": "pointerdown 启动 400ms 延时后以 90ms setInterval 连发，pointerup/pointerleave/pointercancel 全部终止并解绑；数值 clamp 到 [min,max] 后同步禁用越界方向按钮，变化时 remove→void offsetWidth→add 重放弹动动画，output[aria-live] 播报当前值。"
    },
    "effectTags": [
      "步进器",
      "长按连发",
      "边界禁用",
      "微交互",
      "表单"
    ]
  },
  "tag-input": {
    "terms": {
      "zh": "标签输入框",
      "en": "Tag Input",
      "aliases": [
        "标签选择器",
        "chip 输入",
        "Tags Input"
      ],
      "pattern": "Tag Input · Chips Field",
      "principle": "tags 数组是唯一数据源，render() 全量重建 chips 插到输入框之前；Enter 添加（trim + 压缩连续空白 + 去重 + 上限 5 校验），输入框为空时 Backspace 删除末位；报错靠移除 class 后 void offsetWidth 强制 reflow 再加回，实现抖动动画可重复播放。"
    },
    "effectTags": [
      "标签",
      "chip",
      "去重",
      "微交互",
      "表单"
    ]
  },
  "tree-select": {
    "terms": {
      "zh": "树形选择器",
      "en": "Tree Select",
      "aliases": [
        "层级勾选树",
        "级联复选树",
        "Checkbox Tree"
      ],
      "pattern": "Tree Select · Cascading Checkbox",
      "principle": "用 :scope > .tr-children 限定直接子列表确定父子链：勾选向下同步所有后代 checkbox，子级变化后向上逐级重算父级的 checked / indeterminate 三态。"
    },
    "effectTags": [
      "树形",
      "级联选择",
      "半选",
      "表单",
      "勾选"
    ]
  },
  "animated-tabs": {
    "terms": {
      "zh": "滑动指示器标签页",
      "en": "Animated Tabs / Sliding Indicator",
      "aliases": [
        "选项卡",
        "滑动下划线 Tabs",
        "标签切换"
      ],
      "pattern": "Tabs · WAI-ARIA Tab Pattern",
      "principle": "白色指示器是 absolute 元素，切换时实测目标 tab 的 offsetLeft/offsetWidth 写入 transform 与 width 滑过去（非写死位置），resize 时重算；面板用 hidden 切换 + 入场动画。"
    },
    "effectTags": [
      "标签页",
      "滑动指示器",
      "键盘导航",
      "几何实测"
    ]
  },
  "bottom-sheet": {
    "terms": {
      "zh": "底部弹层",
      "en": "Bottom Sheet",
      "aliases": [
        "底部抽屉",
        "分享面板",
        "下拉关闭弹层"
      ],
      "pattern": "Bottom Sheet · Drag-to-dismiss",
      "principle": "把手 pointerdown 后 setPointerCapture 并加 is-dragging 暂停过渡，translateY 直接跟手；松手时位移 >90px、或（>24px 且瞬时速度 >0.22px/ms）即关闭，否则清空 transform 弹回。"
    },
    "effectTags": [
      "底部弹层",
      "拖拽手势",
      "甩动关闭",
      "移动端"
    ]
  },
  "breadcrumb": {
    "terms": {
      "zh": "面包屑",
      "en": "Breadcrumb",
      "aliases": [
        "路径导航",
        "层级导航",
        "面包屑导航"
      ],
      "pattern": "Breadcrumb · Hierarchical Path",
      "principle": "ol>li 语义列表，:not(:last-child)::after 用 5px 的旋转 45° 边框方块画出箭头分隔符，全程纯 CSS 无 JS；药丸变体把伪元素换成 content:'/'，超长标签用 text-overflow 单行截断。"
    },
    "effectTags": [
      "面包屑",
      "路径导航",
      "纯 CSS",
      "截断"
    ]
  },
  "collapsible-sidebar": {
    "terms": {
      "zh": "可折叠侧边栏",
      "en": "Collapsible Sidebar",
      "aliases": [
        "图标侧栏",
        "收起侧边栏",
        "迷你侧栏"
      ],
      "pattern": "Sidebar Collapse · Icon Rail",
      "principle": "data-collapsed 切换宽度 216px↔64px（width 过渡 0.28s），标签与品牌名 opacity 渐隐，折叠态用 data-tip + ::after 在图标右侧 10px 处弹出 tooltip，圆形把手骑在右边框上。"
    },
    "effectTags": [
      "侧边栏",
      "折叠",
      "图标导航",
      "tooltip"
    ]
  },
  "command-menu": {
    "terms": {
      "zh": "命令面板",
      "en": "Command Palette / ⌘K Menu",
      "aliases": [
        "命令菜单",
        "快捷操作面板",
        "Spotlight"
      ],
      "pattern": "Command Palette · Fuzzy Search",
      "principle": "⌘K/Ctrl+K 全局开关面板；fuzzyScore 做子序列匹配（label 与 keywords，keywords 得分 ×0.8、连续命中每字符 +2、完整包含再 +10），按分排序后按 group 插入分组标题，↑↓ 取模循环、Enter 执行。"
    },
    "effectTags": [
      "命令面板",
      "模糊搜索",
      "键盘优先",
      "⌘K"
    ]
  },
  "drawer": {
    "terms": {
      "zh": "侧滑抽屉",
      "en": "Side Drawer / Slide-over Panel",
      "aliases": [
        "侧边抽屉",
        "滑出面板",
        "购物车抽屉"
      ],
      "pattern": "Overlay · Slide-in Drawer",
      "principle": "hidden 控制挂载、is-open 类驱动 translateX(±100%)→0 过渡；打开前双 rAF 等待首帧重排保证入场动画，关闭等 transitionend 加 350ms 兜底再卸载。"
    },
    "effectTags": [
      "抽屉",
      "浮层",
      "遮罩",
      "焦点管理"
    ]
  },
  "dropdown-menu": {
    "terms": {
      "zh": "下拉菜单",
      "en": "Dropdown Menu",
      "aliases": [
        "操作菜单",
        "下拉选项",
        "菜单按钮"
      ],
      "pattern": "Menu Button · WAI-ARIA Menu",
      "principle": "工厂函数 createDropdown 管理每个实例：hidden 挂载 + aria-expanded 同步，↑↓ 取模循环移动焦点，Home/End 跳首尾，ESC 关闭并归还焦点，document pointerdown 在容器外时关闭。"
    },
    "effectTags": [
      "下拉菜单",
      "键盘导航",
      "无障碍",
      "浮层"
    ]
  },
  "filters-sidebar": {
    "terms": {
      "zh": "筛选侧栏",
      "en": "Filters Sidebar / Faceted Filter",
      "aliases": [
        "多面筛选",
        "商品筛选",
        "筛选面板"
      ],
      "pattern": "Faceted Filtering · Sidebar + Chips",
      "principle": "关键词、分类复选组、价格滑杆、有货开关四组条件任一 input/change 都触发 apply() 全量重算，结果列表、匹配数与可移除条件 chips 同步渲染；≤640px 侧栏折叠为按钮开关的抽屉。"
    },
    "effectTags": [
      "筛选",
      "多面过滤",
      "chips",
      "滑杆"
    ]
  },
  "floating-dock": {
    "terms": {
      "zh": "悬浮 Dock",
      "en": "Floating Dock / macOS Magnify Bar",
      "aliases": [
        "Dock 栏",
        "放大坞",
        "鱼眼菜单"
      ],
      "pattern": "Dock Magnification · Proximity Scaling",
      "principle": "dock 上只挂一个 pointermove，对每个图标算光标到其中心的水平距离，1 - distance/110 得放大系数写入 CSS 变量 --magnify，transform 用 calc 换算成缩放与上浮。"
    },
    "effectTags": [
      "Dock",
      "光标跟随",
      "放大",
      "磁性"
    ]
  },
  "gooey-morph-menu": {
    "terms": {
      "zh": "黏液形变菜单",
      "en": "Gooey Morph Menu",
      "aliases": [
        "黏性菜单",
        "液态菜单",
        "SVG goo 菜单"
      ],
      "pattern": "Morphing Menu · SVG Gooey Filter",
      "principle": "触发块与面板是两个独立纯色块，共同包在 filter: url(#gm-goo) 的装饰层里，feGaussianBlur(8) 加 feColorMatrix(alpha 22/-10) 让二者靠近时黏连出液桥，交互层用 z-index 叠在滤镜之上保持文字清晰。"
    },
    "effectTags": [
      "黏液",
      "SVG 滤镜",
      "形变",
      "液态"
    ]
  },
  "mega-menu": {
    "terms": {
      "zh": "大型菜单",
      "en": "Mega Menu",
      "aliases": [
        "超级菜单",
        "多列下拉",
        "导航面板"
      ],
      "pattern": "Navigation · Mega Menu / Hover Intent",
      "principle": "pointerenter 延迟 80ms 才打开（防误扫）、pointerleave 延迟 200ms 才关闭（移动缓冲），触屏/键盘走点击 toggle，ESC 与点击外部均可关闭。"
    },
    "effectTags": [
      "大型菜单",
      "悬停意图",
      "多列",
      "导航"
    ]
  },
  "minimal-navbar": {
    "terms": {
      "zh": "极简导航栏",
      "en": "Minimal Navbar",
      "aliases": [
        "顶部导航",
        "页头导航",
        "响应式导航栏"
      ],
      "pattern": "Responsive Navbar · Scroll-aware Header",
      "principle": "sticky 定位，滚动容器监听 scroll（passive），scrollTop>8 时切 data-scrolled 触发毛玻璃描边；活动链接下划线用 ::after 动画，≤719px 隐藏链接组、汉堡按钮 toggle hidden 移动菜单并同步 aria-expanded。"
    },
    "effectTags": [
      "导航栏",
      "滚动感知",
      "毛玻璃",
      "响应式"
    ]
  },
  "mobile-menu": {
    "terms": {
      "zh": "全屏移动菜单",
      "en": "Full-screen Mobile Menu",
      "aliases": [
        "全屏抽屉",
        "汉堡全屏菜单",
        "移动端覆盖菜单"
      ],
      "pattern": "Overlay Menu · Staggered Reveal",
      "principle": "overlay 用 hidden 控制挂载、data-open 驱动入场；每个链接带 --i 索引，animation-delay 用 calc(var(--i) * 55ms + 60ms) 错峰上升；汉堡三条线按 aria-expanded 变形为叉，关闭 300ms 后再 hidden 并归还焦点。"
    },
    "effectTags": [
      "全屏菜单",
      "错峰入场",
      "汉堡",
      "移动端"
    ]
  },
  "pagination": {
    "terms": {
      "zh": "分页器",
      "en": "Pagination / Stable Page Window",
      "aliases": [
        "页码条",
        "翻页器"
      ],
      "pattern": "Pagination · Sliding Window",
      "principle": "pageWindow() 按 siblings=1 计算窗口序列：首末页常驻、当前页左右各留 1 页、断口补省略号；slots = siblings*2 + 5，总页数不超过 slots 时全量铺开。"
    },
    "effectTags": [
      "分页",
      "页码",
      "窗口算法",
      "键盘可达"
    ]
  },
  "scroll-spy": {
    "terms": {
      "zh": "滚动监听导航",
      "en": "Scroll Spy Nav",
      "aliases": [
        "锚点高亮",
        "文章目录",
        "scrollspy"
      ],
      "pattern": "Scroll Spy · Section Affordance",
      "principle": "IntersectionObserver 监听各小节，取最靠近视口顶部的可见节为当前节，同步高亮左导航对应项；点击锚点用 scrollIntoView smooth，且目标设 scroll-margin-top 防被粘性头部遮挡。"
    },
    "effectTags": [
      "滚动监听",
      "锚点",
      "导航"
    ]
  },
  "step-nav": {
    "terms": {
      "zh": "步骤导航条",
      "en": "Step Navigation / Stepper",
      "aliases": [
        "Stepper",
        "分步条",
        "向导步骤条"
      ],
      "pattern": "Stepper · Wizard Flow",
      "principle": "状态机维护 current 索引，paint() 按 i<current 标 is-done、i===current 标 is-current，大于 current 的步骤按钮直接 disabled 锁定。"
    },
    "effectTags": [
      "步骤条",
      "流程",
      "状态机",
      "进度"
    ]
  },
  "tree-menu": {
    "terms": {
      "zh": "树形菜单",
      "en": "Tree Menu",
      "aliases": [
        "树导航",
        "多级菜单",
        "tree view"
      ],
      "pattern": "Tree · Disclosure Navigation",
      "principle": "每一级是嵌套的 details 式结构：分组按钮 aria-expanded 控制子列表 grid-rows 0fr→1fr 展开收起；当前叶子项用 aria-current 高亮；缩进层级线用 padding + ::before 竖线。"
    },
    "effectTags": [
      "树形菜单",
      "折叠",
      "导航"
    ]
  },
  "accordion": {
    "terms": {
      "zh": "手风琴",
      "en": "Accordion",
      "aliases": [
        "折叠面板",
        "展开收起",
        "Collapsible"
      ],
      "pattern": "Disclosure · Accordion",
      "principle": "面板用 display:grid + grid-template-rows 0fr→1fr 过渡实现高度自适应展开，内层必须 overflow:hidden；JS 只切换 aria-expanded 与 open 类。"
    },
    "effectTags": [
      "折叠展开",
      "高度自适应",
      "FAQ",
      "无障碍"
    ]
  },
  "badge-chip": {
    "terms": {
      "zh": "徽章与标签",
      "en": "Badge & Chip",
      "aliases": [
        "状态标签",
        "可移除 Chip",
        "呼吸圆点"
      ],
      "pattern": "Badge · Status Indicator",
      "principle": "胶囊标签用半透明同色背景叠文字色实现五档状态；圆点靠 ::after 放大淡出的 2s 循环动画做呼吸；移除标签先加 is-leaving 缩放淡出、transitionend 后再删节点。"
    },
    "effectTags": [
      "徽章",
      "状态",
      "呼吸",
      "轻交互"
    ]
  },
  "callout": {
    "terms": {
      "zh": "提示条",
      "en": "Callout / Alert",
      "aliases": [
        "警告条",
        "通知条",
        "alert",
        "callout"
      ],
      "pattern": "Callout · Inline Feedback Banner",
      "principle": "语义档位只换两处 CSS 变量（--co-accent 与 --co-bg），结构固定为左色条、图标、标题正文与关闭按钮；关闭时加类名播放折叠动画后移除节点，aria-live 让读屏软件感知。"
    },
    "effectTags": [
      "提示条",
      "警告",
      "反馈"
    ]
  },
  "checkbox-card": {
    "terms": {
      "zh": "勾选复选框",
      "en": "Animated Checkbox / Checkbox Card",
      "aliases": [
        "对勾动画",
        "卡片式选项",
        "自定义 checkbox"
      ],
      "pattern": "Form Control · Checkbox",
      "principle": "隐藏原生 input，用 :checked 兄弟选择器驱动样式；对勾是 SVG 描边，stroke-dashoffset 16→0 完成描边弹入。"
    },
    "effectTags": [
      "表单",
      "勾选",
      "描边动画",
      "纯 CSS"
    ]
  },
  "context-menu": {
    "terms": {
      "zh": "右键菜单",
      "en": "Context Menu",
      "aliases": [
        "上下文菜单",
        "自定义 contextmenu",
        "长按菜单"
      ],
      "pattern": "Overlay · Context Menu",
      "principle": "拦截 contextmenu 事件，在 pointer 坐标显示 fixed 定位菜单；打开后先量自身尺寸再 clamp 进视口 8px 内边距，触屏用 500ms 长按等效触发。"
    },
    "effectTags": [
      "右键菜单",
      "overlay",
      "长按",
      "键盘导航"
    ]
  },
  "copy-button": {
    "terms": {
      "zh": "复制按钮",
      "en": "Copy Button / Copy to Clipboard",
      "aliases": [
        "剪贴板按钮",
        "代码复制",
        "copy to clipboard"
      ],
      "pattern": "Action · Clipboard Feedback",
      "principle": "优先 navigator.clipboard.writeText，非安全上下文回退隐藏 textarea + execCommand；成功后切到 is-copied 态换对勾，定时 1.6s 复原。"
    },
    "effectTags": [
      "复制",
      "剪贴板",
      "成功反馈",
      "工具按钮"
    ]
  },
  "countdown-timer": {
    "terms": {
      "zh": "倒计时",
      "en": "Countdown Timer",
      "aliases": [
        "倒计时器",
        "秒杀倒计时",
        "countdown"
      ],
      "pattern": "Countdown · Flip Digits",
      "principle": "setInterval 每秒把剩余时间拆成天/时/分/秒写入对应格子；数字变化时给旧值加向上退出动画、新值加进入动画，用 animationend 清理；剩余 ≤10 秒时容器加紧急态类变红脉冲。"
    },
    "effectTags": [
      "倒计时",
      "翻牌",
      "定时"
    ]
  },
  "counter-badge": {
    "terms": {
      "zh": "计数徽章",
      "en": "Counter Badge / Notification Badge",
      "aliases": [
        "未读角标",
        "数字角标",
        "Badge"
      ],
      "pattern": "Indicator · Status Badge",
      "principle": "绝对定位在图标右上角的圆角胶囊，数字超上限时截断文本加「+」，变化时用重排重启 keyframes 做一次弹性放大。"
    },
    "effectTags": [
      "徽章",
      "计数",
      "弹性",
      "状态提示"
    ]
  },
  "heat-map-calendar": {
    "terms": {
      "zh": "贡献热力图",
      "en": "Contribution Heat Map / GitHub Graph",
      "aliases": [
        "热力图",
        "提交日历",
        "activity graph"
      ],
      "pattern": "DataViz · Calendar Heat Map",
      "principle": "CSS Grid 用 grid-auto-flow: column + 7 行让格子按列（周）填充，等级映射五档背景色；提示是 fixed 定位节点跟随 pointermove。"
    },
    "effectTags": [
      "热力图",
      "数据可视化",
      "CSS Grid",
      "悬浮提示"
    ]
  },
  "kbd-shortcut": {
    "terms": {
      "zh": "快捷键标签",
      "en": "Keyboard Shortcut Label / Kbd",
      "aliases": [
        "键帽",
        "kbd 组件",
        "组合键标签"
      ],
      "pattern": "Kbd · Skeuomorphic Keycap",
      "principle": "kbd 键帽用白→灰渐变 + 底边 2px 加粗模拟浮雕，:active 时底边变 1px 并 translateY(1px) 制造按压下沉；组合键只是多个 kbd 横排。"
    },
    "effectTags": [
      "键帽",
      "拟物",
      "纯 CSS",
      "快捷键"
    ]
  },
  "link-hover": {
    "terms": {
      "zh": "链接悬停动效",
      "en": "Link Hover Effect",
      "aliases": [
        "下划线动画",
        "文字上滚",
        "hover underline"
      ],
      "pattern": "Micro-interaction · Link Hover",
      "principle": "用 ::after/::before 伪元素 + transform/width 过渡做下划线与色块，文字上滚则靠双层文本 translateY(-100%)。"
    },
    "effectTags": [
      "悬停",
      "下划线",
      "纯 CSS",
      "导航"
    ]
  },
  "popover": {
    "terms": {
      "zh": "点击浮层",
      "en": "Popover",
      "aliases": [
        "弹出层",
        "气泡卡片",
        "popover"
      ],
      "pattern": "Popover · Anchored Overlay",
      "principle": "浮层绝对定位于触发元素的相对容器内，先渲染后测量（getBoundingClientRect）判断上下空间翻转方向；全局 click 捕获阶段判断 target 是否在浮层外实现点外关闭，Esc 走 keydown 监听。"
    },
    "effectTags": [
      "浮层",
      "弹出",
      "交互"
    ]
  },
  "rating-stars": {
    "terms": {
      "zh": "评分星",
      "en": "Star Rating",
      "aliases": [
        "星级评分",
        "半星评分",
        "rate"
      ],
      "pattern": "Rating · Input Control",
      "principle": "五角星用 clip-path polygon 绘制，灰色轨道层上叠一层 overflow:hidden 的填充层，JS 按评分百分比写 width；指针横向位置小于星宽 50% 判半星。"
    },
    "effectTags": [
      "评分",
      "半星",
      "clip-path",
      "键盘可达"
    ]
  },
  "scroll-shadow": {
    "terms": {
      "zh": "滚动边缘阴影",
      "en": "Scroll Shadow",
      "aliases": [
        "滚动指示",
        "边缘渐隐",
        "scroll indicator"
      ],
      "pattern": "Scroll Shadow · Edge Fade Hint",
      "principle": "容器外层叠两个 fixed 尺寸的渐变遮罩（上白下透明 / 下白上透明），scroll 事件里按 scrollTop 是否大于 0 / 小于最大值切换遮罩 opacity；内容被裁切时阴影出现，暗示「下面还有」。"
    },
    "effectTags": [
      "滚动",
      "阴影",
      "提示"
    ]
  },
  "scroll-to-top": {
    "terms": {
      "zh": "回到顶部按钮",
      "en": "Scroll to Top / Back to Top Button",
      "aliases": [
        "回顶 FAB",
        "返回顶部",
        "进度环回顶"
      ],
      "pattern": "Scroll Utility · Floating Action Button",
      "principle": "scroll 监听里算出滚动进度写入 SVG 圆的 stroke-dashoffset，超过一屏 60% 才解除 hidden 浮现，点击 scrollTo 平滑回顶。"
    },
    "effectTags": [
      "滚动",
      "进度环",
      "SVG",
      "长页面"
    ]
  },
  "segmented-control": {
    "terms": {
      "zh": "分段控件",
      "en": "Segmented Control",
      "aliases": [
        "分段切换器",
        "滑块 Tabs",
        "iOS Segmented"
      ],
      "pattern": "Segmented Control · Tabs",
      "principle": "选中态由原生 radio 的 :checked 驱动，JS 只测量选中项的 offsetLeft/offsetWidth 写给绝对定位的白色滑块，键盘与表单语义因此免费获得。"
    },
    "effectTags": [
      "分段切换",
      "滑块跟随",
      "radio",
      "Tabs"
    ]
  },
  "speed-dial": {
    "terms": {
      "zh": "悬浮操作组",
      "en": "Speed Dial / FAB Actions",
      "aliases": [
        "展开式 FAB",
        "浮动菜单",
        "speed dial"
      ],
      "pattern": "FAB · Speed Dial",
      "principle": "FAB 切换 is-open 类：子操作列解除 hidden 并按 --i × 40ms 逐个 stagger 弹入，加号 rotate(45deg) 变关闭；外点与 ESC 收起。"
    },
    "effectTags": [
      "FAB",
      "stagger",
      "弹出",
      "操作组"
    ]
  },
  "spinner-set": {
    "terms": {
      "zh": "加载器合集",
      "en": "CSS Spinner Set / Loaders",
      "aliases": [
        "加载动画",
        "loading 图标",
        "转圈"
      ],
      "pattern": "Loader · Loading Indicator",
      "principle": "全部用 border 画环、transform 旋转与 opacity/scale 循环关键帧实现，多元素 loader 靠 animation-delay 错峰，不碰 JS 与重排属性。"
    },
    "effectTags": [
      "加载",
      "纯 CSS",
      "循环动画",
      "合集"
    ]
  },
  "theme-toggle": {
    "terms": {
      "zh": "明暗切换开关",
      "en": "Theme Toggle / Day-Night Switch",
      "aliases": [
        "日夜开关",
        "太阳月亮开关",
        "dark mode toggle"
      ],
      "pattern": "Toggle · Theme Switch",
      "principle": "button 承载 role=switch + aria-checked，JS 切 is-on 类；太阳/月亮两层 SVG 靠 opacity 与 rotate±60°/scale 交叉淡变，滑块用带过冲的弹簧缓动滑入深夜蓝轨道。"
    },
    "effectTags": [
      "主题切换",
      "图标交叉淡变",
      "回弹",
      "switch 语义"
    ]
  },
  "timeline": {
    "terms": {
      "zh": "垂直时间线",
      "en": "Vertical Timeline / Stepper",
      "aliases": [
        "步骤条",
        "进度时间线",
        "timeline"
      ],
      "pattern": "Timeline · Progress Steps",
      "principle": "每项 grid 两列（18px 节点列 + 内容列），连接线画在 ::before 上并用 bottom: -14px 抵消 grid gap 让线段跨项连续，最后一段 display:none 收尾。"
    },
    "effectTags": [
      "时间线",
      "步骤",
      "进度状态",
      "纯 CSS"
    ]
  },
  "toast-stack": {
    "terms": {
      "zh": "通知提示",
      "en": "Toast / Snackbar",
      "aliases": [
        "通知堆叠",
        "消息条",
        "toast"
      ],
      "pattern": "Toast · Transient Notification",
      "principle": "倒计时就是底部进度条的 CSS 动画（animationend 即定时器），悬停暂停动画即暂停关闭；退场先量真实高度写入 --ts-h，负 margin 收拢让排队通知平滑上移。"
    },
    "effectTags": [
      "通知",
      "堆叠",
      "倒计时",
      "aria-live"
    ]
  },
  "toggle-group": {
    "terms": {
      "zh": "多选按钮组",
      "en": "Toggle Group",
      "aliases": [
        "切换按钮组",
        "多选组",
        "toggle buttons"
      ],
      "pattern": "Toggle Group · Multi-select Pills",
      "principle": "每个选项是 aria-pressed 的 button，选中态 = 主色描边 + 浅底 + 右上角勾选角标；容器不做单选互斥，全选/清空按钮批量同步 aria-pressed 并派发 change。"
    },
    "effectTags": [
      "多选",
      "筛选",
      "按钮组"
    ]
  },
  "toggle-switch": {
    "terms": {
      "zh": "开关",
      "en": "Toggle Switch",
      "aliases": [
        "切换开关",
        "滑动开关",
        "switch"
      ],
      "pattern": "Form Control · Toggle",
      "principle": "隐藏 checkbox 保留原生语义，:checked + 兄弟选择器让 44×24 轨道换色、18px 滑块 translateX(20px)，全程纯 CSS 零 JS。"
    },
    "effectTags": [
      "开关",
      "表单",
      "纯 CSS",
      "键盘可达"
    ]
  },
  "tooltip-css": {
    "terms": {
      "zh": "气泡提示",
      "en": "CSS Tooltip",
      "aliases": [
        "气泡",
        "悬浮提示",
        "tooltip"
      ],
      "pattern": "Tooltip · Overlay Hint",
      "principle": "提示本体是 ::after（content: attr(data-tip)），箭头是旋转 45° 的 6px ::before 方块；hover 与 :focus-visible 双通道触发，opacity+visibility 过渡淡入。"
    },
    "effectTags": [
      "悬浮提示",
      "纯 CSS",
      "四方向",
      "键盘可达"
    ]
  },
  "circular-progress": {
    "terms": {
      "zh": "环形进度环",
      "en": "Circular Progress Ring",
      "aliases": [
        "进度环",
        "圆环进度",
        "Radial Progress"
      ],
      "pattern": "Progress Indicator · SVG Stroke",
      "principle": "SVG 圆设置 pathLength=100 归一化周长，用 stroke-dashoffset 从 100 减到 100-p 露出弧长，CSS transition 平滑填充。"
    },
    "effectTags": [
      "进度",
      "圆环",
      "SVG",
      "描边",
      "百分比"
    ]
  },
  "dot-loader": {
    "terms": {
      "zh": "三点加载动画",
      "en": "Three-Dot Bouncing Loader",
      "aliases": [
        "三点弹跳",
        "打字机加载",
        "Typing Loader"
      ],
      "pattern": "Loading Indicator · Staggered Bounce",
      "principle": "三个圆点共用同一组 bounce 关键帧，靠 animation-delay 0.15s 逐个错峰，30% 处 translateY(-7px) 升起并恢复不透明度。"
    },
    "effectTags": [
      "加载",
      "圆点",
      "弹跳",
      "错峰",
      "纯 CSS"
    ]
  },
  "linear-progress": {
    "terms": {
      "zh": "线性进度条",
      "en": "Linear Progress Bar",
      "aliases": [
        "水平进度条",
        "进度条",
        "不定进度条"
      ],
      "pattern": "Progress Indicator · Determinate / Indeterminate",
      "principle": "轨道内一个填充 div，确定模式改 width 百分比并同步 aria-valuenow；不定模式用 40% 宽的渐变条以 translateX 扫动循环。"
    },
    "effectTags": [
      "进度",
      "进度条",
      "不定进度",
      "可访问性",
      "扫动"
    ]
  },
  "multi-step-progress": {
    "terms": {
      "zh": "多步骤进度",
      "en": "Multi-Step Progress / Stepper",
      "aliases": [
        "步骤条",
        "向导进度",
        "Stepper"
      ],
      "pattern": "Wizard / Stepper · Segmented Progress",
      "principle": "一排状态圆点压在一条 2px 连接线上，线内填充层宽度 = (current-1)/(total-1)，data-state 驱动已完成/当前/待办三种样式。"
    },
    "effectTags": [
      "进度",
      "步骤条",
      "向导",
      "结账流程",
      "状态机"
    ]
  },
  "page-loader": {
    "terms": {
      "zh": "页面启动加载",
      "en": "Page Splash Loader",
      "aliases": [
        "启动屏",
        "开屏加载",
        "Splash Screen"
      ],
      "pattern": "Splash Screen · Staged Fake Progress",
      "principle": "全屏 fixed 启动层按预设阶段推进分段进度，走完后设 data-done 触发 opacity+visibility 双过渡淡出并交接 aria-hidden。"
    },
    "effectTags": [
      "加载",
      "启动屏",
      "全屏",
      "淡出",
      "品牌"
    ]
  },
  "scroll-progress": {
    "terms": {
      "zh": "滚动进度条",
      "en": "Scroll Progress Bar",
      "aliases": [
        "阅读进度条",
        "阅读进度指示器"
      ],
      "pattern": "Scroll-linked Progress · Reading Progress",
      "principle": "监听滚动容器 scroll 事件，用 scrollTop / (scrollHeight - clientHeight) 算出比例，rAF 节流后写入顶部 sticky 条的宽度。"
    },
    "effectTags": [
      "进度",
      "滚动",
      "阅读进度",
      "固定顶栏",
      "性能"
    ]
  },
  "skeleton-card": {
    "terms": {
      "zh": "骨架屏",
      "en": "Skeleton Screen",
      "aliases": [
        "Ghost Loading",
        "Content Placeholder",
        "Shimmer Placeholder",
        "占位骨架"
      ],
      "pattern": "Loading State · Perceived Performance",
      "principle": "用与真实内容同尺寸的灰色占位块先占住布局，再叠加一条横向掠过的渐变高光表示「正在来」；数据到达后原位替换，视觉上零跳动。"
    },
    "effectTags": [
      "加载",
      "占位",
      "扫光",
      "等待"
    ]
  },
  "skeleton-table": {
    "terms": {
      "zh": "表格骨架屏",
      "en": "Table Skeleton Screen",
      "aliases": [
        "骨架屏",
        "加载占位",
        "Shimmer 占位"
      ],
      "pattern": "Skeleton Screen · Shimmer",
      "principle": "用 grid 按真实列权重复制一行行微光条占位，shimmer 靠 background-position 在 400% 宽的渐变上扫动，数据到达后原位替换不跳动。"
    },
    "effectTags": [
      "骨架屏",
      "shimmer",
      "加载占位",
      "表格",
      "无障碍"
    ]
  },
  "upload-progress": {
    "terms": {
      "zh": "上传进度卡片",
      "en": "Upload Progress Card",
      "aliases": [
        "文件上传行",
        "上传卡片",
        "Transfer Row"
      ],
      "pattern": "File Upload · Determinate Progress + Transfer Controls",
      "principle": "rAF 每帧按速度 × dt 累加已传字节，渲染百分比/大小/速度三读数；data-state 状态机（running/paused/done/cancelled）驱动暂停色与按钮可用性。"
    },
    "effectTags": [
      "进度",
      "上传",
      "文件",
      "暂停",
      "状态机"
    ]
  },
  "logo-bolt-hex": {
    "terms": {
      "zh": "闪电六边形标志",
      "en": "Bolt Hex Logo",
      "aliases": [
        "六边形logo",
        "闪电标志",
        "hex logo"
      ],
      "pattern": "Logo Mark · Hex + Negative Bolt",
      "principle": "六边形用三点坐标的多边形 fill 渐变，闪电以白色负形叠在中心，整体外扩 2px 安全区保证小尺寸可辨。"
    },
    "effectTags": [
      "logo",
      "渐变",
      "品牌"
    ]
  },
  "logo-diamond-stack": {
    "terms": {
      "zh": "叠层菱形标志",
      "en": "Diamond Stack Logo",
      "aliases": [
        "菱形logo",
        "层叠标志",
        "diamond logo"
      ],
      "pattern": "Logo Mark · Offset Layers",
      "principle": "前后两个菱形（旋转 45° 的正方形）错位叠加，后层低透明度表达层次，前层实色渐变压住重心。"
    },
    "effectTags": [
      "logo",
      "叠层",
      "渐变"
    ]
  },
  "logo-hive": {
    "terms": {
      "zh": "蜂巢标志",
      "en": "Hive Logo",
      "aliases": [
        "蜂巢logo",
        "六边形标志",
        "hive logo"
      ],
      "pattern": "Logo Mark · Honeycomb Trio",
      "principle": "三枚正六边形两下一上拼接，深浅两种透明度区分层次，表达群体协作。"
    },
    "effectTags": [
      "logo",
      "蜂巢",
      "协作"
    ]
  },
  "logo-leaf-ring": {
    "terms": {
      "zh": "绿叶圆环标志",
      "en": "Leaf Ring Logo",
      "aliases": [
        "叶子logo",
        "圆环标志",
        "leaf logo"
      ],
      "pattern": "Logo Mark · Ring + Leaf Negative",
      "principle": "粗描边圆环（stroke 3）承载品牌色渐变，叶片以两段贝塞尔曲线闭合，白梗细线制造负形层次。"
    },
    "effectTags": [
      "logo",
      "环保",
      "渐变"
    ]
  },
  "logo-orbit": {
    "terms": {
      "zh": "星轨环绕标志",
      "en": "Orbit Logo",
      "aliases": [
        "轨道logo",
        "星球标志",
        "orbit logo"
      ],
      "pattern": "Logo Mark · Core + Orbit Ring",
      "principle": "中心实心球 + 椭圆轨道（rotate -30°）+ 轨道上的亮点卫星，三元素渐变同源，形成运动感。"
    },
    "effectTags": [
      "logo",
      "轨道",
      "科技"
    ]
  },
  "logo-sun-mark": {
    "terms": {
      "zh": "朝阳标志",
      "en": "Sun Mark Logo",
      "aliases": [
        "太阳logo",
        "朝阳标志",
        "sun logo"
      ],
      "pattern": "Logo Mark · Half Sun + Rays",
      "principle": "半轮圆形承担主体，放射短线环绕上缘表达光芒，下缘水平线做地平线，重心稳且向上。"
    },
    "effectTags": [
      "logo",
      "朝阳",
      "渐变"
    ]
  },
  "logo-tri-prism": {
    "terms": {
      "zh": "棱镜三角标志",
      "en": "Tri Prism Logo",
      "aliases": [
        "三角logo",
        "棱镜标志",
        "prism logo"
      ],
      "pattern": "Logo Mark · Overlapping Triangles",
      "principle": "两枚同形三角形错位叠放，靠透明度与色相差异表达「折射」，负空间形成第三枚虚三角。"
    },
    "effectTags": [
      "logo",
      "棱镜",
      "渐变"
    ]
  },
  "logo-wave-shield": {
    "terms": {
      "zh": "浪盾标志",
      "en": "Wave Shield Logo",
      "aliases": [
        "盾牌logo",
        "安全标志",
        "shield logo"
      ],
      "pattern": "Logo Mark · Shield + Waves",
      "principle": "盾形以中轴对称的多边形表达可靠，双波浪负形削弱硬朗感，上下留白均衡。"
    },
    "effectTags": [
      "logo",
      "安全",
      "渐变"
    ]
  },
  "404-page": {
    "terms": {
      "zh": "404 页面",
      "en": "404 Not Found Page",
      "aliases": [
        "错误页",
        "Not Found 落地页"
      ],
      "pattern": "Error Page · 巨型数字 + 站内搜索",
      "principle": "居中堆叠巨型 404 数字（中间 0 拆成独立 span 做 CSS 悬浮呼吸）、站内搜索框与双操作按钮；按 / 或 ⌘K 聚焦搜索，返回按钮优先 history.back()。"
    },
    "effectTags": [
      "404",
      "悬浮呼吸",
      "径向光晕",
      "快捷键",
      "页面模板"
    ]
  },
  "analytics-dashboard": {
    "terms": {
      "zh": "数据分析仪表盘",
      "en": "Analytics Dashboard",
      "aliases": [
        "数据看板",
        "后台仪表盘",
        "Dashboard"
      ],
      "pattern": "Dashboard · 侧边栏 + 统计卡 + SVG 折线图",
      "principle": "208px 粘性侧边栏 + 主区统计卡/图表/表格；折线图用 JS 生成确定性伪随机序列（种子 42）再拼 SVG polyline；统计数字用 requestAnimationFrame 做 1400ms 缓出 count-up，访客数每 2.2s 轻微漂移模拟实时。"
    },
    "effectTags": [
      "仪表盘",
      "SVG 折线图",
      "数字滚动",
      "实时模拟",
      "侧边栏布局"
    ]
  },
  "blog-home": {
    "terms": {
      "zh": "博客首页",
      "en": "Blog Home Page",
      "aliases": [
        "博客门户",
        "内容站首页",
        "文章列表页"
      ],
      "pattern": "Content Site · 头条大卡 + 文章网格",
      "principle": "顶部导航 + 一张双栏头条大卡 + 三列文章卡网格 + RSS 底栏；所有封面用 CSS 渐变与半透明圆形装饰绘制，零图片资源；640px 以下头条与网格同时降为单列。"
    },
    "effectTags": [
      "博客",
      "头条大卡",
      "CSS 渐变封面",
      "三列网格",
      "零图片"
    ]
  },
  "changelog-page": {
    "terms": {
      "zh": "更新日志页",
      "en": "Changelog Page",
      "aliases": [
        "版本日志",
        "发布记录",
        "release notes"
      ],
      "pattern": "Changelog · Version Timeline",
      "principle": "两栏布局：左栏粘性版本锚点列表（IntersectionObserver 监听右侧版本块进入视口后高亮对应锚点），右栏每版一块——版本号 + 日期 + 三类变更条目（新增绿 / 修复红 / 优化蓝）用色点标签区分。"
    },
    "effectTags": [
      "更新日志",
      "时间轴",
      "版本"
    ]
  },
  "checkout-page": {
    "terms": {
      "zh": "结算页",
      "en": "Checkout Page",
      "aliases": [
        "收银台",
        "下单页",
        "结账页"
      ],
      "pattern": "Commerce · 表单 + 订单摘要双栏",
      "principle": "左 1.4fr 收货与支付表单、右 1fr 订单摘要；支付方式用隐藏 radio + :checked + 相邻选择器实现卡片高亮（零 JS 状态）；运费按满 ¥1000 免邮规则在 JS 里计算；提交时校验必填并聚焦第一个缺失项。"
    },
    "effectTags": [
      "结算",
      "表单校验",
      "订单摘要",
      "卡片单选",
      "满额免邮"
    ]
  },
  "coming-soon": {
    "terms": {
      "zh": "Coming Soon 页面",
      "en": "Coming Soon Landing Page",
      "aliases": [
        "预热页",
        "倒计时落地页",
        "Teaser Page"
      ],
      "pattern": "Teaser Landing · 倒计时 + 通知表单",
      "principle": "径向光晕背景上居中徽章+大标题+四格倒计时+邮箱表单；倒计时目标取固定日期（2026-12-31 +08:00），已过期自动顺延 30 天保证演示永远有数，setInterval 每秒刷新且数字用 tabular-nums 防跳动。"
    },
    "effectTags": [
      "倒计时",
      "预热落地页",
      "通知表单",
      "径向光晕",
      "每秒刷新"
    ]
  },
  "docs-page": {
    "terms": {
      "zh": "文档站模板",
      "en": "Documentation Page Template",
      "aliases": [
        "文档站布局",
        "Docs 三栏布局",
        "知识库页面"
      ],
      "pattern": "Docs Layout · 三栏 + Scroll-spy 目录",
      "principle": "190px 站内导航 + 正文卡 + 150px 页内目录三栏网格，两侧 sticky；目录高亮用 IntersectionObserver（rootMargin -12%/-70%）监听标题进入视口上带，标题设 scroll-margin-top 防锚点贴顶，无 IO 环境退化为点击高亮。"
    },
    "effectTags": [
      "文档站",
      "三栏布局",
      "scroll-spy",
      "锚点导航",
      "sticky 侧栏"
    ]
  },
  "empty-state": {
    "terms": {
      "zh": "空状态页面",
      "en": "Empty State Page",
      "aliases": [
        "零数据页",
        "占位页",
        "No Data"
      ],
      "pattern": "Empty State · 纯 CSS 插画卡片",
      "principle": "三张居中卡片并排，各自用纯 CSS（border 圆环、伪元素拼形状）画搜索/收件箱/建项目三种 84px 插画；文案遵循「现状说明 + 下一步动作」，每个状态配一个明确按钮。"
    },
    "effectTags": [
      "空状态",
      "纯 CSS 插画",
      "引导文案",
      "卡片",
      "零图片"
    ]
  },
  "gallery-page": {
    "terms": {
      "zh": "图库灯箱页",
      "en": "Gallery Lightbox Page",
      "aliases": [
        "灯箱图库",
        "作品集画廊",
        "Lightbox Gallery"
      ],
      "pattern": "Gallery · 错落网格 + 灯箱",
      "principle": "12 幅程序化双色渐变作品（无图片资源）组成 4 列网格，第 3n+1 张跨两行形成错落节奏；点击打开全屏灯箱，键盘方向键/按钮循环切换、ESC 与遮罩点击关闭，关闭后焦点归还给触发按钮。"
    },
    "effectTags": [
      "灯箱",
      "图库",
      "焦点管理",
      "键盘导航",
      "CSS 渐变作品"
    ]
  },
  "help-center": {
    "terms": {
      "zh": "帮助中心页",
      "en": "Help Center",
      "aliases": [
        "帮助页",
        "支持中心",
        "FAQ page"
      ],
      "pattern": "Help Center · Search-first Support",
      "principle": "搜索优先的单列布局：大号搜索框置顶并在输入时联动过滤下方分类文章列表；分类卡片用图标 + 标题 + 篇数聚合入口；空结果态给出反馈引导换词。"
    },
    "effectTags": [
      "帮助中心",
      "搜索",
      "模板"
    ]
  },
  "kanban-board": {
    "terms": {
      "zh": "看板模板",
      "en": "Kanban Board Template",
      "aliases": [
        "任务看板",
        "拖拽看板",
        "Board"
      ],
      "pattern": "Kanban Board · HTML5 拖拽 + 状态驱动渲染",
      "principle": "数据数组（state）驱动全量渲染三列卡片；HTML5 DnD 拖拽跨列，dragover 时按 clientY 与卡片中点比较插入 2px 指示线，drop 后写回 state 重渲染；每张卡带 ◀ ▶ 按钮作为键盘友好的移动回退。"
    },
    "effectTags": [
      "看板",
      "拖拽排序",
      "HTML5 DnD",
      "指示线",
      "键盘回退"
    ]
  },
  "login-page": {
    "terms": {
      "zh": "极简登录页",
      "en": "Minimal Login Page",
      "aliases": [
        "登录注册页",
        "Auth 页面",
        "Glass Login"
      ],
      "pattern": "Auth · 居中卡片表单",
      "principle": "视口居中一张玻璃卡片，极光 blob 在底层缓慢漂移提供氛围；表单内联校验通过 aria-invalid 标红，密码可见性由按钮切换 input.type。"
    },
    "effectTags": [
      "登录",
      "玻璃拟态",
      "表单校验",
      "极光背景",
      "响应式"
    ]
  },
  "portfolio-home": {
    "terms": {
      "zh": "作品集主页",
      "en": "Portfolio Home Page",
      "aliases": [
        "个人主页",
        "设计师主页",
        "个人站"
      ],
      "pattern": "Portfolio · 编辑排版 + 作品网格",
      "principle": "单列编辑式排版：超大 clamp 姓名标题压住首屏，作品网格用 auto-fit 布局，四个项目视觉全部由 CSS 渐变 + 单个 <i> 元素（进度条/瓶身/圆环/线条）抽象绘制，零图片；页脚大号邮箱链接收尾。"
    },
    "effectTags": [
      "作品集",
      "编辑排版",
      "超大标题",
      "CSS 抽象图形",
      "零图片"
    ]
  },
  "pricing-page": {
    "terms": {
      "zh": "定价页",
      "en": "Pricing Page",
      "aliases": [
        "套餐页",
        "价格表",
        "订阅方案"
      ],
      "pattern": "Marketing · 定价卡片 + 月付/年付切换",
      "principle": "三档套餐卡片由 auto-fit 网格排布，月付/年付开关（role=switch）切换时从每张卡片的 data-monthly / data-annual 属性实时重算金额；推荐档位用描边+阴影+顶部徽章高亮，FAQ 用原生 details/summary 折叠。"
    },
    "effectTags": [
      "定价",
      "套餐切换",
      "手风琴",
      "高亮徽章",
      "响应式"
    ]
  },
  "product-detail": {
    "terms": {
      "zh": "商品详情页",
      "en": "Product Detail Page",
      "aliases": [
        "PDP",
        "电商商品页",
        "单品页"
      ],
      "pattern": "E-commerce · 画廊 + 变体选择",
      "principle": "左图右信息两栏网格；商品主视觉与缩略图全部用 CSS 渐变占位（无图片资源），颜色变体以 radiogroup 语义切换并同步主图/缩略图/价格，数量步进实时更新加购合计，加购后按钮短暂变绿反馈。"
    },
    "effectTags": [
      "电商",
      "变体切换",
      "数量步进",
      "加购反馈",
      "纯 CSS 占位"
    ]
  },
  "saas-landing": {
    "terms": {
      "zh": "SaaS 营销落地页",
      "en": "SaaS Landing Page",
      "aliases": [
        "Marketing Site",
        "Product Landing Page",
        "Conversion Page",
        "产品首页"
      ],
      "pattern": "Conversion Landing Page · Above the Fold",
      "principle": "首屏用一句话价值主张加单一主行动按钮建立认知，随后用功能区、社会证明、FAQ 逐层消除疑虑，页脚收口兜住长尾流量。"
    },
    "effectTags": [
      "落地页",
      "营销",
      "整站",
      "转化"
    ]
  },
  "settings-template": {
    "terms": {
      "zh": "设置页面",
      "en": "Settings Page",
      "aliases": [
        "偏好设置",
        "账户设置",
        "Settings 表单页"
      ],
      "pattern": "App Shell · 侧栏分区 + 表单行",
      "principle": "168px 粘性分区导航 + 右侧白卡分区表单；脏检查对比输入框初始值驱动底部悬浮保存条；危险区按钮采用两步确认（3 秒内二次点击才执行）而非弹窗。"
    },
    "effectTags": [
      "设置",
      "脏检查",
      "保存条",
      "两步确认",
      "开关"
    ]
  },
  "status-page": {
    "terms": {
      "zh": "系统状态页",
      "en": "Status Page",
      "aliases": [
        "服务状态",
        "监控页",
        "uptime page"
      ],
      "pattern": "Status · Uptime Board",
      "principle": "顶部全宽横幅用颜色表达整体状态（绿=正常），每个服务一行：状态灯 + 名称 + 90 天可用率条（90 根 2px 竖条按日着色）；事件时间线倒序列出故障记录与持续时长。"
    },
    "effectTags": [
      "状态页",
      "监控",
      "可用率"
    ]
  },
  "team-page": {
    "terms": {
      "zh": "团队介绍页",
      "en": "Team Page",
      "aliases": [
        "关于我们",
        "成员列表",
        "about us",
        "team grid"
      ],
      "pattern": "About · Team Roster",
      "principle": "首屏使命宣言 + 4 项统计数字；成员网格按职能筛选（全部/工程/设计/运营），卡片 = 渐变头像占位 + 姓名 + 职位 + 社交图标；底部招聘横幅引导投递。"
    },
    "effectTags": [
      "团队页",
      "筛选",
      "计数动画"
    ]
  }
};
