import type { UIResourceMeta } from "@/types/resource";

export const meta: UIResourceMeta = {
  id: "liquid-button",
  slug: "liquid-button",
  name: "液态按钮",
  description: "悬停时旋转的液态填充从底部升起。纯 CSS 实现，无需 JavaScript。",
  category: "buttons",
  subcategory: "Buttons",
  type: "component",
  tags: ["按钮", "液态", "悬停", "纯 CSS"],
  technologies: ["HTML", "CSS", "React"],
  styles: ["活泼", "渐变"],
  difficulty: "intermediate",
  featured: true,
  popular: true,
  responsive: true,
  previewBackground: "light",
  compatibility: ["Chrome 90+", "Firefox 90+", "Safari 15+", "Edge 90+"],
  author: "VibeUI Team",
  version: "1.0.0",
  createdAt: "2026-07-02",
  updatedAt: "2026-08-14",
  dir: "components/buttons/liquid-button",
};
